// This file is auto-generated by @hey-api/openapi-ts

export type AIProviderInfo = {
    id: string;
    name: string;
    available: boolean;
    default_model: string;
    models: Array<(string)>;
};

export type AIProvidersPublic = {
    providers: Array<AIProviderInfo>;
};

export type AnalysisPublic = {
    id: string;
    repo_id: string;
    workflow_file_id?: (string | null);
    workflow_file_path?: (string | null);
    repo_full_name?: (string | null);
    content_hash: string;
    status: AnalysisStatus;
    score?: (number | null);
    grade?: (string | null);
    triggered_by: AnalysisTrigger;
    branch?: (string | null);
    commit_sha?: (string | null);
    created_at?: (string | null);
    completed_at?: (string | null);
};

export type AnalysisStatus = 'queued' | 'running' | 'completed' | 'failed' | 'no_workflows';

export type AnalysisTrigger = 'webhook_push' | 'webhook_workflow_run' | 'polled_push' | 'manual' | 'scheduled' | 'release';

export type BatchFixRequest = {
    issue_ids?: (Array<(string)> | null);
};

/**
 * The billing page's headline: plan, payment state, and usage.
 *
 * ``tier`` is the purchased plan and ``effective_tier`` is what limits are
 * actually being applied — they differ exactly when a subscription is
 * ``unpaid`` or ``canceled``, and showing both is what lets the UI say "Pro,
 * currently limited to Free" instead of silently misreporting one or other.
 */
export type BillingSubscriptionPublic = {
    id: string;
    tier: UserTier;
    effective_tier: UserTier;
    status: SubscriptionStatus;
    analyses_used: number;
    fixes_used: number;
    repos_used?: number;
    period_start?: (string | null);
    period_end?: (string | null);
    grace_expires_at?: (string | null);
    cancel_at_period_end?: boolean;
    trial_end?: (string | null);
    billing_enabled?: boolean;
};

export type Body_auth_github_callback = {
    grant_type?: (string | null);
    code: string;
    client_id?: (string | null);
    redirect_uri?: (string | null);
    code_verifier?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CheckoutRequest = {
    tier: UserTier;
};

/**
 * The Stripe-hosted URL the browser must be sent to.
 */
export type CheckoutSessionPublic = {
    url: string;
};

/**
 * Aggregate CI outcome for a PR, from ``check_suite`` webhooks.
 */
export type CIStatus = 'pending' | 'success' | 'failure' | 'none';

export type CloudAccountCreate = {
    org_id: string;
    display_name: string;
    role_arn: string;
    regions?: Array<(string)>;
};

export type CloudAccountPublic = {
    id: string;
    org_id: string;
    provider: CloudProvider;
    display_name: string;
    role_arn?: (string | null);
    external_id: string;
    regions?: Array<(string)>;
    status: CloudAccountStatus;
    last_synced_at?: (string | null);
    latest_score?: (number | null);
    latest_grade?: (string | null);
    created_at?: (string | null);
};

export type CloudAccountStatus = 'pending_verification' | 'connected' | 'error' | 'disabled';

export type CloudFindingPublic = {
    id: string;
    scan_id: string;
    rule_id: string;
    rule_slug: string;
    severity: IssueSeverity;
    category: IssueCategory;
    message: string;
    context?: (string | null);
    status: FindingStatus;
    created_at?: (string | null);
    resolved_at?: (string | null);
    resolution_reason?: (FindingResolutionReason | null);
    cloud_account_id: string;
    resource_type: string;
    resource_id: string;
    region?: (string | null);
};

export type CloudProvider = 'aws';

export type CloudScanPublic = {
    id: string;
    status: ScanStatus;
    triggered_by: AnalysisTrigger;
    score?: (number | null);
    grade?: (string | null);
    error_message?: (string | null);
    created_at?: (string | null);
    completed_at?: (string | null);
    cloud_account_id: string;
    region?: (string | null);
    resource_count?: number;
};

/**
 * One image build (and optionally its containers) observed in CI.
 *
 * A workflow can build several images, so this is posted once per image
 * rather than once per run — which is exactly why it is not folded into
 * TelemetryPayload.
 */
export type DockerBuildPayload = {
    workflow_run_id: number;
    image_ref?: (string | null);
    dockerfile_path?: (string | null);
    image_size_bytes?: (number | null);
    context_size_bytes?: (number | null);
    build_duration_ms?: (number | null);
    cache_hit_ratio?: (number | null);
    layers?: (Array<{
    [key: string]: unknown;
}> | null);
    containers?: (Array<{
    [key: string]: unknown;
}> | null);
};

/**
 * One measured build, with the findings its measurements produced.
 *
 * ``layers`` and ``containers`` are stored as JSON text (they are
 * collector-shaped and never queried relationally) and decoded here, so the
 * frontend never parses a string out of a typed field.
 */
export type DockerBuildTelemetryPublic = {
    id: string;
    workflow_run_id: number;
    image_ref?: (string | null);
    dockerfile_path?: (string | null);
    image_size_bytes?: (number | null);
    context_size_bytes?: (number | null);
    build_duration_ms?: (number | null);
    cache_hit_ratio?: (number | null);
    layers?: Array<{
        [key: string]: unknown;
    }>;
    containers?: Array<{
        [key: string]: unknown;
    }>;
    collected_at?: (string | null);
    findings?: Array<DockerRuntimeFindingPublic>;
};

/**
 * A Dockerfile or Compose file's live source for a target.
 *
 * Not persisted (mirroring ``TerraformFilePublic``): fetched from GitHub on
 * demand, so it carries no id/branch — just path and content. ``kind`` lets
 * the viewer pick a syntax highlighter without re-deriving it from the name.
 */
export type DockerFilePublic = {
    path: string;
    raw_content: string;
    kind: string;
};

export type DockerFindingPublic = {
    id: string;
    scan_id: string;
    rule_id: string;
    rule_slug: string;
    severity: IssueSeverity;
    category: IssueCategory;
    message: string;
    context?: (string | null);
    status: FindingStatus;
    created_at?: (string | null);
    resolved_at?: (string | null);
    resolution_reason?: (FindingResolutionReason | null);
    fix_id?: (string | null);
    fix_status?: (FixStatus | null);
    docker_target_id: string;
    file_path: string;
    service_name?: (string | null);
    stage_name?: (string | null);
    line_start?: (number | null);
    line_end?: (number | null);
};

export type DockerFixGenerateRequest = {
    finding_ids?: (Array<(string)> | null);
};

export type DockerFixPublic = {
    id: string;
    file_path: string;
    pr_id?: (string | null);
    llm_provider: LLMProvider;
    llm_model: string;
    status: FixStatus;
    full_content?: (string | null);
    error_message?: (string | null);
    pr_url?: (string | null);
    pr_branch?: (string | null);
    pr_state?: (PullRequestState | null);
    created_at?: (string | null);
    delivered_at?: (string | null);
    docker_target_id: string;
};

/**
 * One ``DockerBuildEnrichment`` dressed for the Runtime tab.
 *
 * The stored row carries only a rule slug; severity, category and title are
 * resolved from the rule catalog here so the tab can sort and colour without
 * a second request. All three are nullable because a Rego rule shipped
 * without a seed entry in ``core/db.py`` still evaluates and still produces
 * enrichments — it just has no catalog row to describe it.
 */
export type DockerRuntimeFindingPublic = {
    id: string;
    telemetry_id: string;
    rule_slug: string;
    rule_title?: (string | null);
    severity?: (IssueSeverity | null);
    category?: (IssueCategory | null);
    evidence: string;
    recommendation: string;
    created_at?: (string | null);
};

export type DockerRuntimeFixRequest = {
    enrichment_ids: Array<(string)>;
};

export type DockerScanPublic = {
    id: string;
    status: ScanStatus;
    triggered_by: AnalysisTrigger;
    score?: (number | null);
    grade?: (string | null);
    error_message?: (string | null);
    created_at?: (string | null);
    completed_at?: (string | null);
    branch?: (string | null);
    commit_sha?: (string | null);
    docker_target_id: string;
    file_count?: (number | null);
};

export type DockerTargetCreate = {
    repo_id: string;
    root_path?: string;
};

export type DockerTargetPublic = {
    id: string;
    repo_id: string;
    repo_full_name?: (string | null);
    root_path: string;
    enabled: boolean;
    last_scanned_at?: (string | null);
    last_scanned_head_sha?: (string | null);
    latest_score?: (number | null);
    latest_grade?: (string | null);
    badge_sig?: (string | null);
};

/**
 * Lifecycle of the dynamic-analysis enrichment for a ``completed``-phase
 * telemetry run.
 *
 * Distinct from ``TelemetryPhase`` (an ingest category — ``started`` and
 * ``completed`` are separate rows): this tracks the worker that turns a
 * completed run's metrics into persisted ``DynamicEnrichment`` findings.
 */
export type DynamicAnalysisStatus = 'queued' | 'running' | 'enriched' | 'failed';

/**
 * A runtime-telemetry finding, exposed for the frontend.
 *
 * Deliberately thinner than ``IssuePublic``: enrichments carry no severity,
 * category, status/lifecycle, line numbers, or fix linkage, so they are
 * presented as their own "Runtime findings" class rather than merged into the
 * static issue list.
 */
export type DynamicEnrichmentPublic = {
    id: string;
    telemetry_run_id: string;
    workflow_run_id?: (number | null);
    rule_slug: string;
    evidence: string;
    recommendation: string;
    created_at?: (string | null);
};

/**
 * How much of what could be scanned actually has been.
 *
 * ``enabled`` means different things per engine — a bool column for Docker
 * and Terraform targets, ``CloudAccountStatus.connected`` for a cloud
 * account. The CI engine's target is a ``WorkflowFile``, which has no enable
 * switch at all, so there ``enabled == total``.
 */
export type EngineCoverageStat = {
    total: number;
    enabled: number;
    scanned: number;
    never_scanned: number;
    latest_scan_failed: number;
};

export type EngineFindingStat = {
    open: number;
    resolved: number;
    critical_open: number;
    by_severity: Array<SeverityStat>;
    by_category: Array<IssueCategoryStat>;
};

/**
 * Open findings bucketed by the state of the fix addressing them.
 *
 * ``unfixed`` mirrors ``list_issues(unfixed=True)``: no fix row at all, or a
 * fix in one of the rejected/superseded states. The buckets are disjoint and
 * sum to ``EngineFindingStat.open``.
 */
export type EngineFixPipelineStat = {
    unfixed: number;
    in_progress: number;
    ready: number;
    delivered: number;
    landed: number;
    failed: number;
};

export type EngineFreshnessStat = {
    last_completed_scan_at: (string | null);
    last_scan_at: (string | null);
};

export type EngineOverview = {
    engine: OverviewEngineKey;
    section: OverviewSection;
    label: string;
    coverage: EngineCoverageStat;
    freshness: EngineFreshnessStat;
    score: EngineScoreStat;
    findings: EngineFindingStat;
    fixes: (EngineFixPipelineStat | null);
    top_rules: Array<TopRuleStat>;
};

/**
 * Average of each target's latest *completed* scan score.
 *
 * A target whose latest scan failed keeps the score of its last good scan —
 * the same rule ``api/mappers/base.latest_completed_scan`` applies per
 * target, so a grade here always matches the one that engine's own list
 * endpoint reports.
 */
export type EngineScoreStat = {
    avg_score: (number | null);
    grade: (string | null);
    scored_targets: number;
    by_grade: Array<GradeStat>;
};

export type ExternalRepositoryCreate = {
    full_name: string;
    installation_id?: (number | null);
};

export type FindingResolutionReason = 'no_longer_detected' | 'target_removed';

/**
 * Lifecycle of a TerraformFinding or CloudFinding.
 *
 * Unlike ``Issue.status`` (owned by a DB trigger reacting to ``fix_id``),
 * findings in this delivery have no fix/PR concept yet (see plan Phase 7),
 * so the application sets this column directly alongside resolved_at/
 * ignored_at rather than needing trigger-derived state.
 */
export type FindingStatus = 'open' | 'resolved' | 'ignored';

export type FixDeliveryMode = 'pr' | 'comment' | 'disabled';

export type FixIssueSummary = {
    id: string;
    rule_slug?: (string | null);
    severity?: (IssueSeverity | null);
    category?: (IssueCategory | null);
    message?: (string | null);
    line_start?: (number | null);
    line_end?: (number | null);
};

export type FixPublic = {
    id: string;
    workflow_file_id: string;
    workflow_file_path?: (string | null);
    repo_id?: (string | null);
    pr_id?: (string | null);
    llm_provider: LLMProvider;
    llm_model: string;
    status: FixStatus;
    full_content?: (string | null);
    base_content?: (string | null);
    error_message?: (string | null);
    pr_url?: (string | null);
    pr_branch?: (string | null);
    pr_state?: (PullRequestState | null);
    comment_url?: (string | null);
    created_at?: (string | null);
    delivered_at?: (string | null);
    issues?: Array<FixIssueSummary>;
};

export type FixStatus = 'pending' | 'generating' | 'ready' | 'delivering' | 'delivered' | 'failed' | 'rejected_by_user' | 'superseded_by_closed_pr' | 'superseded_by_deleted_file' | 'landed';

/**
 * How many scan targets currently hold this grade.
 *
 * Emitted for every rung of ``services.scoring.GRADE_LADDER`` in order, best
 * first, plus any grade found in the data that isn't on the ladder — grades
 * are free-form ``VARCHAR(8)``, so a row written before a ladder change must
 * still be counted rather than silently dropped.
 */
export type GradeStat = {
    grade: string;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InstallationSyncRequest = {
    code: string;
    redirect_uri?: (string | null);
};

export type InvoicePublic = {
    id: string;
    stripe_invoice_id: string;
    number?: (string | null);
    status: InvoiceStatus;
    amount_due_cents: number;
    amount_paid_cents: number;
    currency: string;
    hosted_invoice_url?: (string | null);
    invoice_pdf?: (string | null);
    period_start?: (string | null);
    period_end?: (string | null);
    paid_at?: (string | null);
    created_at?: (string | null);
};

/**
 * Mirrors Stripe's invoice statuses, minus ``deleted`` (drafts only).
 */
export type InvoiceStatus = 'draft' | 'open' | 'paid' | 'void' | 'uncollectible';

export type IssueCategory = 'energy' | 'reliability' | 'security' | 'performance' | 'maintainability';

export type IssueCategoryStat = {
    category: IssueCategory;
    open: number;
    resolved: number;
    critical_open: number;
};

export type IssuePublic = {
    id: string;
    analysis_id: string;
    rule_id: string;
    rule_slug: string;
    severity: IssueSeverity;
    category: IssueCategory;
    line_start?: (number | null);
    line_end?: (number | null);
    message: string;
    context?: (string | null);
    status: IssueStatus;
    created_at?: (string | null);
    resolved_at?: (string | null);
    resolution_reason?: (IssueResolutionReason | null);
    needs_manual_work?: boolean;
    manual_work_note?: (string | null);
    fix_id?: (string | null);
    fix_status?: (FixStatus | null);
    workflow_file_path?: (string | null);
};

/**
 * Why an issue was resolved — an attribute of the ``resolved`` state.
 *
 * Kept as a column rather than splitting ``resolved`` into several states so
 * the issue graph stays small. Set alongside ``resolved_at`` and cleared when
 * a resolved violation recurs.
 *
 * - ``no_longer_detected``: absent from the latest analysis (a manual fix or a
 * disabled/removed rule — the two cannot be told apart after the fact).
 * - ``file_removed``: the workflow file was deleted or renamed.
 * - ``merged``: the fix PR was merged, applying the change to the branch.
 * - ``branch_deleted``: the branch carrying the issue's workflow file was
 * deleted; the violation no longer exists anywhere to fix.
 */
export type IssueResolutionReason = 'no_longer_detected' | 'file_removed' | 'merged' | 'branch_deleted';

export type IssueSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

/**
 * Exact issue counts, computed by SQL aggregation rather than fetched and
 * counted client-side — unaffected by any page's ``skip``/``limit``.
 */
export type IssueStatsPublic = {
    total_open: number;
    total_resolved: number;
    critical_open: number;
    by_category: Array<IssueCategoryStat>;
    by_repo?: Array<RepoIssueStats>;
};

/**
 * Derived lifecycle of an issue.
 *
 * This value is a persisted column computed by a database trigger from
 * ``ignored_at``, ``resolved_at`` and ``fix_id`` (see ``Issue.status`` and
 * migrations ``0022``/``0026``). ``ignored`` takes precedence over the other
 * states so a user-dismissed violation stays muted regardless of fix/resolve
 * activity.
 */
export type IssueStatus = 'open' | 'fix_in_progress' | 'resolved' | 'ignored';

export type LLMProvider = 'openai' | 'anthropic' | 'gemini' | 'ollama';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrganizationAIUpdate = {
    default_llm_provider?: (LLMProvider | null);
    default_llm_model?: (string | null);
};

export type OrganizationPublic = {
    id: string;
    name: string;
    tier: UserTier;
    default_llm_provider?: (LLMProvider | null);
    default_llm_model?: (string | null);
    fix_delivery_mode: FixDeliveryMode;
    created_at?: (string | null);
};

export type OssApplicationCreate = {
    repo_url: string;
    license_name: string;
    justification: string;
};

export type OssApplicationPublic = {
    id: string;
    user_id: string;
    repo_url: string;
    license_name: string;
    justification: string;
    status: OssApplicationStatus;
    review_note?: (string | null);
    reviewed_at?: (string | null);
    created_at?: (string | null);
};

export type OssApplicationReview = {
    approve: boolean;
    review_note?: (string | null);
};

/**
 * Review state of a request for the granted open-source plan.
 */
export type OssApplicationStatus = 'pending' | 'approved' | 'rejected' | 'withdrawn';

/**
 * Which analysis engine a block of dashboard overview stats describes.
 *
 * A presentation-layer key, not a persisted column — ``Rule.domain`` stays
 * the DB-level discriminator. The two exist because they don't line up:
 * ``container_docker`` and ``container_runtime`` rules both produce findings
 * on the Docker engine, so one key covers two domains.
 */
export type OverviewEngineKey = 'ci' | 'docker' | 'terraform' | 'cloud';

export type OverviewPublic = {
    generated_at: string;
    totals: OverviewTotals;
    engines: Array<EngineOverview>;
};

/**
 * Which collapsible dashboard section an engine renders under.
 *
 * Four engines, three sections: the Infrastructure page already shows
 * Terraform and cloud posture as sibling tabs, so the dashboard groups them
 * the same way rather than inventing a fourth top-level heading.
 */
export type OverviewSection = 'ci' | 'docker' | 'infra';

/**
 * All-engine roll-up for the dashboard's summary header.
 *
 * ``avg_score`` is the unweighted mean of the per-engine averages that
 * exist, not of every target: averaging targets directly would let a repo
 * with forty workflow files drown out a failing cloud posture.
 */
export type OverviewTotals = {
    targets: number;
    enabled_targets: number;
    never_scanned_targets: number;
    open_findings: number;
    resolved_findings: number;
    critical_open: number;
    avg_score: (number | null);
    grade: (string | null);
    by_severity: Array<SeverityStat>;
    by_category: Array<IssueCategoryStat>;
    engines_with_data: number;
};

/**
 * ``None`` means unlimited, at every layer up to the UI.
 */
export type PlanLimitsPublic = {
    analyses?: (number | null);
    fixes?: (number | null);
    repos?: (number | null);
};

export type PlanPublic = {
    tier: UserTier;
    name: string;
    price_cents: number;
    price_display: string;
    tagline: string;
    limits: PlanLimitsPublic;
    auto_fix: boolean;
    public_repos_only: boolean;
    is_purchasable: boolean;
    features?: Array<(string)>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type PullRequestPublic = {
    id: string;
    repo_id: string;
    pr_branch: string;
    pr_url?: (string | null);
    pr_state?: (PullRequestState | null);
    ci_status?: (CIStatus | null);
    review_decision?: (ReviewDecision | null);
    mergeable_state?: (string | null);
    externally_modified?: boolean;
    comment_url?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type PullRequestState = 'open' | 'draft' | 'merged' | 'closed';

/**
 * A repo's open-issue counts and severity-weighted grade for one category.
 *
 * ``score``/``grade`` are ``None`` when the repo has no overall grade yet
 * (e.g. no completed analysis). See ``RepoIssueStats`` for how categories
 * are grouped per repo.
 */
export type RepoCategoryStat = {
    category: IssueCategory;
    open: number;
    critical_open: number;
    score?: (number | null);
    grade?: (string | null);
};

/**
 * Per-repo issue breakdown — powers the dashboard's category health star
 * diagram. Only populated on the unscoped (all-repos) stats call;
 * meaningless once already filtered to a single ``repo_id``.
 *
 * ``score``/``grade`` here are the repo's own overall grade (same values as
 * ``RepositoryPublic.avg_score``/``grade``), repeated so the frontend
 * doesn't need a second lookup to size the radar's "no issues" fallback.
 * Each entry in ``categories`` covers every ``IssueCategory``, including
 * categories with zero open issues, so their scores average out to exactly
 * the repo's overall score (see ``compute_category_scores``).
 */
export type RepoIssueStats = {
    repo_id: string;
    score?: (number | null);
    grade?: (string | null);
    categories?: Array<RepoCategoryStat>;
};

export type RepositoryPublic = {
    id: string;
    org_id: string;
    full_name: string;
    enabled: boolean;
    is_accessible?: boolean;
    is_external?: boolean;
    is_private?: boolean;
    default_branch: string;
    auto_fix_enabled?: boolean;
    tier?: (UserTier | null);
    badge_sig?: (string | null);
    created_at?: (string | null);
    avg_score?: (number | null);
    grade?: (string | null);
};

/**
 * Latest human review decision for a PR, from ``pull_request_review``.
 */
export type ReviewDecision = 'approved' | 'changes_requested' | 'review_required';

export type RulePublic = {
    id: string;
    slug: string;
    category: IssueCategory;
    severity: IssueSeverity;
    title: string;
    description: string;
    enabled: boolean;
};

export type SamplePayload = {
    workflow_run_id: number;
    cpu_percent?: (number | null);
    ram_used_mb?: (number | null);
    disk_used_gb?: (number | null);
    net_bytes_sent?: (number | null);
    net_bytes_recv?: (number | null);
    top_processes?: (Array<{
    [key: string]: unknown;
}> | null);
};

/**
 * Lifecycle of a TerraformScan or CloudScan.
 *
 * Deliberately separate from ``AnalysisStatus``: that enum's ``no_workflows``
 * value is workflow-specific vocabulary. ``no_targets`` covers both "no .tf
 * files under this root" and "no resources of the scanned types in this
 * account/region".
 */
export type ScanStatus = 'queued' | 'running' | 'completed' | 'failed' | 'no_targets';

/**
 * Open/resolved finding counts for one severity.
 *
 * Emitted for every ``IssueSeverity`` including zeros, so the frontend can
 * render a fixed-segment severity bar without gap logic.
 */
export type SeverityStat = {
    severity: IssueSeverity;
    open: number;
    resolved: number;
};

export type SSESignal = 'analysis.queued' | 'analysis.started' | 'analysis.completed' | 'analysis.failed' | 'analysis.skipped' | 'analysis.no_workflows' | 'fix.skipped' | 'fix.pending' | 'fix.generating' | 'fix.ready' | 'fix.delivering' | 'fix.delivered' | 'fix.failed' | 'fix.rejected' | 'fix.landed' | 'pr.opened' | 'pr.updated' | 'pr.closed' | 'pr.merged' | 'installation.syncing' | 'installation.synced' | 'installation.created' | 'installation.deleted' | 'installation.suspended' | 'installation.unsuspended' | 'installation.updated' | 'repository.added' | 'repository.disabled' | 'repository.toggled' | 'repository.action_pr_opened' | 'repository.suspended' | 'repository.archived' | 'repository.inaccessible' | 'repository.restored' | 'dynamic.queued' | 'dynamic.running' | 'dynamic.enriched' | 'dynamic.failed' | 'analysis.quota_exceeded' | 'subscription.activated' | 'subscription.past_due' | 'subscription.unpaid' | 'subscription.canceled' | 'subscription.updated';

/**
 * Lifecycle of a ``BillingSubscription`` — see ``BillingSubscriptionMachine``.
 *
 * Orthogonal to ``UserTier``: the tier says *what was bought*, this says
 * *whether it is currently being paid for*. The combination is resolved by
 * ``services/billing/lifecycle.effective_tier``, which is the only thing
 * quota enforcement reads.
 *
 * ``past_due`` deliberately keeps full paid service — it is the grace window,
 * not a punishment. Only ``unpaid`` (grace expired) and ``canceled`` fall
 * back to Free limits, and neither ever removes data.
 */
export type SubscriptionStatus = 'incomplete' | 'trialing' | 'active' | 'past_due' | 'unpaid' | 'pending_cancellation' | 'canceled';

/**
 * Averaged telemetry across a repo's runs.
 *
 * Sample-derived fields are averaged over ``TelemetryMetricSample`` rows;
 * run-derived fields (``avg_ram_percent``, ``avg_vcpus``) come from the
 * per-run ``metrics``/``runner_specs`` JSON. Any field is ``None`` when no
 * data supports it.
 */
export type TelemetryAveragePublic = {
    run_count?: number;
    sample_count?: number;
    avg_cpu_percent?: (number | null);
    avg_ram_used_mb?: (number | null);
    avg_ram_percent?: (number | null);
    avg_disk_used_gb?: (number | null);
    avg_net_bytes_sent?: (number | null);
    avg_net_bytes_recv?: (number | null);
    avg_vcpus?: (number | null);
};

export type TelemetryPayload = {
    workflow_run_id: number;
    branch?: string;
    commit_sha?: string;
    workflow_name?: string;
    runner_specs?: {
        [key: string]: unknown;
    };
    metrics?: {
        [key: string]: unknown;
    };
    phase?: TelemetryPhase;
};

export type TelemetryPhase = 'started' | 'completed';

export type TelemetryRunPublic = {
    id: string;
    workflow_run_id: number;
    phase?: (TelemetryPhase | null);
    dynamic_status?: (DynamicAnalysisStatus | null);
    runner_specs?: {
        [key: string]: unknown;
    };
    metrics?: {
        [key: string]: unknown;
    };
    collected_at?: (string | null);
    enrichments?: Array<DynamicEnrichmentPublic>;
};

export type TelemetrySummaryPublic = {
    average: TelemetryAveragePublic;
    runs?: Array<TelemetryRunPublic>;
};

/**
 * A ``.tf`` file's live source for a Terraform root.
 *
 * Terraform files aren't persisted (unlike ``WorkflowFile``); they're fetched
 * from GitHub on demand, so this carries no id/branch — just the path and
 * content, mirroring the shape of ``WorkflowFilePublic``.
 */
export type TerraformFilePublic = {
    path: string;
    raw_content: string;
};

export type TerraformFindingPublic = {
    id: string;
    scan_id: string;
    rule_id: string;
    rule_slug: string;
    severity: IssueSeverity;
    category: IssueCategory;
    message: string;
    context?: (string | null);
    status: FindingStatus;
    created_at?: (string | null);
    resolved_at?: (string | null);
    resolution_reason?: (FindingResolutionReason | null);
    fix_id?: (string | null);
    fix_status?: (FixStatus | null);
    terraform_root_id: string;
    resource_address?: (string | null);
    file_path: string;
    line_start?: (number | null);
    line_end?: (number | null);
    module_path?: (string | null);
    terraform_address?: (string | null);
};

export type TerraformFixGenerateRequest = {
    finding_ids?: (Array<(string)> | null);
};

export type TerraformFixPublic = {
    id: string;
    file_path: string;
    pr_id?: (string | null);
    llm_provider: LLMProvider;
    llm_model: string;
    status: FixStatus;
    full_content?: (string | null);
    error_message?: (string | null);
    pr_url?: (string | null);
    pr_branch?: (string | null);
    pr_state?: (PullRequestState | null);
    created_at?: (string | null);
    delivered_at?: (string | null);
    terraform_root_id: string;
};

export type TerraformRootCreate = {
    repo_id: string;
    root_path: string;
};

export type TerraformRootPublic = {
    id: string;
    repo_id: string;
    repo_full_name?: (string | null);
    root_path: string;
    enabled: boolean;
    last_scanned_at?: (string | null);
    last_scanned_head_sha?: (string | null);
    latest_score?: (number | null);
    latest_grade?: (string | null);
    badge_sig?: (string | null);
};

export type TerraformScanPublic = {
    id: string;
    status: ScanStatus;
    triggered_by: AnalysisTrigger;
    score?: (number | null);
    grade?: (string | null);
    error_message?: (string | null);
    created_at?: (string | null);
    completed_at?: (string | null);
    branch?: (string | null);
    commit_sha?: (string | null);
    terraform_root_id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * A rule ranked by how many open findings it accounts for.
 */
export type TopRuleStat = {
    rule_id: string;
    slug: string;
    title: string;
    severity: IssueSeverity;
    category: IssueCategory;
    open: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * How much of one meter a single engine accounted for this period.
 */
export type UsageBreakdownPublic = {
    meter: UsageMeter;
    engine: UsageEngine;
    quantity: number;
};

/**
 * Which engine produced a usage record.
 *
 * Every one of these debits the same shared pool; the tag exists so a user
 * can see *where* their allowance went, and so tests can assert that each
 * engine is actually metered.
 */
export type UsageEngine = 'workflow' | 'terraform' | 'docker' | 'cloud' | 'telemetry' | 'carryover';

/**
 * Which allowance a usage record draws down.
 *
 * ``repos`` is absent on purpose: it is a live capacity count (how many
 * repositories are enabled right now), not something consumed over time, so
 * it is measured by querying rather than by ledger entries.
 */
export type UsageMeter = 'analyses' | 'fixes';

/**
 * Per-meter usage with the engine split behind it.
 *
 * The breakdown is what answers "why am I at 90%" — before the ledger there
 * was no way to tell a user that their Terraform roots, not their workflows,
 * were spending the allowance.
 */
export type UsagePublic = {
    period_start?: (string | null);
    period_end?: (string | null);
    analyses_used?: number;
    fixes_used?: number;
    repos_used?: number;
    limits: PlanLimitsPublic;
    breakdown?: Array<UsageBreakdownPublic>;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    github_username?: (string | null);
    tier?: UserTier;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserTier = 'free' | 'starter' | 'pro' | 'ultimate' | 'open_source';

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WorkflowDeliverRequest = {
    fix_id: string;
};

export type WorkflowFilePublic = {
    id: string;
    path: string;
    branch?: (string | null);
    raw_content?: (string | null);
};

export type AnalysesListAnalysesData = {
    branch?: (string | null);
    grade?: (string | null);
    limit?: number;
    repoId?: (string | null);
    skip?: number;
    status?: (AnalysisStatus | null);
};

export type AnalysesListAnalysesResponse = (Array<AnalysisPublic>);

export type AnalysesGetAnalysisData = {
    analysisId: string;
};

export type AnalysesGetAnalysisResponse = (AnalysisPublic);

export type AnalysesTriggerAnalysisData = {
    branch?: (string | null);
    force?: boolean;
    repoId: string;
};

export type AnalysesTriggerAnalysisResponse = ({
    [key: string]: (string);
});

export type AnalysesReanalyzeForWorkflowData = {
    force?: boolean;
    workflowFileId: string;
};

export type AnalysesReanalyzeForWorkflowResponse = ({
    [key: string]: (string);
});

export type AnalysesReanalyzeAllResponse = ({
    [key: string]: (string);
});

export type AuthGithubCallbackData = {
    formData: Body_auth_github_callback;
};

export type AuthGithubCallbackResponse = (Token);

export type BadgesGetBadgeData = {
    branch: string;
    owner: string;
    repo: string;
    sig?: (string | null);
};

export type BadgesGetBadgeResponse = (unknown);

export type BadgesGetBadgeJsonData = {
    branch: string;
    owner: string;
    repo: string;
    sig?: (string | null);
};

export type BadgesGetBadgeJsonResponse = ({
    [key: string]: unknown;
});

export type BadgesGetTerraformRootBadgeData = {
    rootId: string;
    sig?: (string | null);
};

export type BadgesGetTerraformRootBadgeResponse = (unknown);

export type BadgesGetTerraformRootBadgeJsonData = {
    rootId: string;
    sig?: (string | null);
};

export type BadgesGetTerraformRootBadgeJsonResponse = ({
    [key: string]: unknown;
});

export type BadgesGetDockerTargetBadgeData = {
    sig?: (string | null);
    targetId: string;
};

export type BadgesGetDockerTargetBadgeResponse = (unknown);

export type BadgesGetDockerTargetBadgeJsonData = {
    sig?: (string | null);
    targetId: string;
};

export type BadgesGetDockerTargetBadgeJsonResponse = ({
    [key: string]: unknown;
});

export type BillingListPlansResponse = (Array<PlanPublic>);

export type BillingGetSubscriptionResponse = (BillingSubscriptionPublic);

export type BillingGetUsageResponse = (UsagePublic);

export type BillingGetTierLimitsResponse = ({
    [key: string]: unknown;
});

export type BillingListInvoicesResponse = (Array<InvoicePublic>);

export type BillingCreateCheckoutData = {
    requestBody: CheckoutRequest;
};

export type BillingCreateCheckoutResponse = (CheckoutSessionPublic);

export type BillingCreatePortalResponse = (CheckoutSessionPublic);

export type BillingListMyOssApplicationsResponse = (Array<OssApplicationPublic>);

export type BillingCreateOssApplicationData = {
    requestBody: OssApplicationCreate;
};

export type BillingCreateOssApplicationResponse = (OssApplicationPublic);

export type BillingListOssApplicationsData = {
    status?: (OssApplicationStatus | null);
};

export type BillingListOssApplicationsResponse = (Array<OssApplicationPublic>);

export type BillingReviewOssApplicationData = {
    applicationId: string;
    requestBody: OssApplicationReview;
};

export type BillingReviewOssApplicationResponse = (OssApplicationPublic);

export type BillingStripeWebhookData = {
    stripeSignature?: (string | null);
};

export type BillingStripeWebhookResponse = ({
    [key: string]: (string);
});

export type CloudCreateCloudAccountData = {
    requestBody: CloudAccountCreate;
};

export type CloudCreateCloudAccountResponse = (CloudAccountPublic);

export type CloudListCloudAccountsData = {
    orgId?: (string | null);
};

export type CloudListCloudAccountsResponse = (Array<CloudAccountPublic>);

export type CloudToggleCloudAccountData = {
    accountId: string;
    enabled: boolean;
};

export type CloudToggleCloudAccountResponse = ({
    [key: string]: (string | boolean);
});

export type CloudDeleteCloudAccountData = {
    accountId: string;
};

export type CloudDeleteCloudAccountResponse = (void);

export type CloudTriggerCloudScanData = {
    accountId: string;
};

export type CloudTriggerCloudScanResponse = ({
    [key: string]: (string);
});

export type CloudListCloudScansData = {
    accountId: string;
};

export type CloudListCloudScansResponse = (Array<CloudScanPublic>);

export type CloudListCloudFindingsData = {
    accountId: string;
    includeResolved?: boolean;
};

export type CloudListCloudFindingsResponse = (Array<CloudFindingPublic>);

export type DockerCreateDockerTargetData = {
    requestBody: DockerTargetCreate;
};

export type DockerCreateDockerTargetResponse = (DockerTargetPublic);

export type DockerListDockerTargetsData = {
    repoId?: (string | null);
};

export type DockerListDockerTargetsResponse = (Array<DockerTargetPublic>);

export type DockerToggleDockerTargetData = {
    targetId: string;
};

export type DockerToggleDockerTargetResponse = ({
    [key: string]: (string | boolean);
});

export type DockerDeleteDockerTargetData = {
    targetId: string;
};

export type DockerDeleteDockerTargetResponse = (void);

export type DockerTriggerDockerScanData = {
    branch?: (string | null);
    targetId: string;
};

export type DockerTriggerDockerScanResponse = ({
    [key: string]: (string);
});

export type DockerListDockerScansData = {
    limit?: number;
    targetId: string;
};

export type DockerListDockerScansResponse = (Array<DockerScanPublic>);

export type DockerListDockerFindingsData = {
    includeResolved?: boolean;
    targetId: string;
};

export type DockerListDockerFindingsResponse = (Array<DockerFindingPublic>);

export type DockerListDockerFilesData = {
    ref?: (string | null);
    targetId: string;
};

export type DockerListDockerFilesResponse = (Array<DockerFilePublic>);

export type DockerListDockerRuntimeData = {
    targetId: string;
};

export type DockerListDockerRuntimeResponse = (Array<DockerBuildTelemetryPublic>);

export type DockerListDockerFixesData = {
    targetId: string;
};

export type DockerListDockerFixesResponse = (Array<DockerFixPublic>);

export type DockerTriggerDockerFixGenerationData = {
    force?: boolean;
    requestBody?: (DockerFixGenerateRequest | null);
    targetId: string;
};

export type DockerTriggerDockerFixGenerationResponse = ({
    [key: string]: (string | number);
});

export type DockerTriggerDockerRuntimeFixGenerationData = {
    force?: boolean;
    requestBody: DockerRuntimeFixRequest;
    targetId: string;
};

export type DockerTriggerDockerRuntimeFixGenerationResponse = ({
    [key: string]: (string | number);
});

export type DockerTriggerDockerDeliveryData = {
    force?: boolean;
    targetId: string;
};

export type DockerTriggerDockerDeliveryResponse = ({
    [key: string]: (string);
});

export type EventsGetSseSignalsResponse = (Array<SSESignal>);

export type EventsCreateSseTicketResponse = ({
    [key: string]: (string | number);
});

export type EventsStreamEventsData = {
    ticket?: (string | null);
};

export type EventsStreamEventsResponse = (unknown);

export type FixesListFixesData = {
    branch?: (string | null);
    limit?: number;
    repoId?: (string | null);
    skip?: number;
    status?: (FixStatus | null);
};

export type FixesListFixesResponse = (Array<FixPublic>);

export type FixesListPullRequestsData = {
    repoId: string;
};

export type FixesListPullRequestsResponse = (Array<PullRequestPublic>);

export type FixesGetFixData = {
    fixId: string;
};

export type FixesGetFixResponse = (FixPublic);

export type FixesRejectFixData = {
    fixId: string;
};

export type FixesRejectFixResponse = (void);

export type FixesTriggerFixGenerationForRepoData = {
    force?: boolean;
    repoId: string;
    requestBody?: BatchFixRequest;
};

export type FixesTriggerFixGenerationForRepoResponse = ({
    [key: string]: (number);
});

export type FixesTriggerWorkflowDeliveryData = {
    force?: boolean;
    requestBody: WorkflowDeliverRequest;
};

export type FixesTriggerWorkflowDeliveryResponse = ({
    [key: string]: (string);
});

export type FixesTriggerRepoDeliveryData = {
    force?: boolean;
    repoId: string;
};

export type FixesTriggerRepoDeliveryResponse = ({
    [key: string]: (string);
});

export type FixesRegenerateFixesForRepoData = {
    repoId: string;
};

export type FixesRegenerateFixesForRepoResponse = ({
    [key: string]: (number);
});

export type FixesRegenerateFixesForWorkflowData = {
    fixId: string;
};

export type FixesRegenerateFixesForWorkflowResponse = ({
    [key: string]: (number);
});

export type FixesRegenerateFailedFixData = {
    fixId: string;
};

export type FixesRegenerateFailedFixResponse = ({
    [key: string]: (string);
});

export type FixesSyncPrStatusesData = {
    repoId: string;
};

export type FixesSyncPrStatusesResponse = ({
    [key: string]: (number);
});

export type InstallationsListInstallationsResponse = (Array<OrganizationPublic>);

export type InstallationsSyncInstallationsData = {
    requestBody: InstallationSyncRequest;
};

export type InstallationsSyncInstallationsResponse = (Array<OrganizationPublic>);

export type IssuesListIssuesData = {
    analysisId?: (string | null);
    branch?: (string | null);
    category?: (IssueCategory | null);
    includeIgnored?: boolean;
    includeResolved?: boolean;
    latestOnly?: boolean;
    limit?: number;
    repoId?: (string | null);
    severity?: (IssueSeverity | null);
    skip?: number;
    unfixed?: boolean;
};

export type IssuesListIssuesResponse = (Array<IssuePublic>);

export type IssuesGetIssueStatsData = {
    branch?: (string | null);
    latestOnly?: boolean;
    repoId?: (string | null);
};

export type IssuesGetIssueStatsResponse = (IssueStatsPublic);

export type IssuesGetIssueData = {
    issueId: string;
};

export type IssuesGetIssueResponse = (IssuePublic);

export type IssuesIgnoreIssueData = {
    issueId: string;
};

export type IssuesIgnoreIssueResponse = (IssuePublic);

export type IssuesUnignoreIssueData = {
    issueId: string;
};

export type IssuesUnignoreIssueResponse = (IssuePublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type OrganizationsListAiProvidersResponse = (AIProvidersPublic);

export type OrganizationsListMyOrganizationsResponse = (Array<OrganizationPublic>);

export type OrganizationsUpdateOrgAiPreferencesData = {
    orgId: string;
    requestBody: OrganizationAIUpdate;
};

export type OrganizationsUpdateOrgAiPreferencesResponse = (OrganizationPublic);

export type OverviewGetOverviewData = {
    orgId?: (string | null);
    topRulesLimit?: number;
};

export type OverviewGetOverviewResponse = (OverviewPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RepositoriesListRepositoriesData = {
    enabled?: (boolean | null);
    limit?: number;
    orgId?: (string | null);
    skip?: number;
};

export type RepositoriesListRepositoriesResponse = (Array<RepositoryPublic>);

export type RepositoriesListExternalRepositoriesData = {
    limit?: number;
    skip?: number;
};

export type RepositoriesListExternalRepositoriesResponse = (Array<RepositoryPublic>);

export type RepositoriesCreateExternalRepositoryData = {
    requestBody: ExternalRepositoryCreate;
};

export type RepositoriesCreateExternalRepositoryResponse = (RepositoryPublic);

export type RepositoriesGetRepositoryData = {
    repoId: string;
};

export type RepositoriesGetRepositoryResponse = (RepositoryPublic);

export type RepositoriesListWorkflowFilesData = {
    branch?: (string | null);
    repoId: string;
};

export type RepositoriesListWorkflowFilesResponse = (Array<WorkflowFilePublic>);

export type RepositoriesToggleRepositoryData = {
    enabled: boolean;
    repoId: string;
};

export type RepositoriesToggleRepositoryResponse = ({
    [key: string]: (string | boolean);
});

export type RepositoriesToggleAutoFixData = {
    enabled: boolean;
    repoId: string;
};

export type RepositoriesToggleAutoFixResponse = ({
    [key: string]: (string | boolean);
});

export type RepositoriesListRepositoryBranchesData = {
    repoId: string;
};

export type RepositoriesListRepositoryBranchesResponse = (Array<(string)>);

export type RepositoriesIntegrateActionData = {
    repoId: string;
};

export type RepositoriesIntegrateActionResponse = ({
    [key: string]: (string);
});

export type RulesListRulesData = {
    category?: (IssueCategory | null);
    enabled?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type RulesListRulesResponse = (Array<RulePublic>);

export type RulesGetRuleData = {
    ruleId: string;
};

export type RulesGetRuleResponse = (RulePublic);

export type RulesToggleRuleData = {
    enabled: boolean;
    ruleId: string;
};

export type RulesToggleRuleResponse = (RulePublic);

export type TelemetryIngestTelemetryData = {
    authorization?: (string | null);
    requestBody: TelemetryPayload;
};

export type TelemetryIngestTelemetryResponse = ({
    [key: string]: (string);
});

export type TelemetryIngestDockerBuildData = {
    authorization?: (string | null);
    requestBody: DockerBuildPayload;
};

export type TelemetryIngestDockerBuildResponse = ({
    [key: string]: (string);
});

export type TelemetryIngestSampleData = {
    authorization?: (string | null);
    requestBody: SamplePayload;
};

export type TelemetryIngestSampleResponse = ({
    [key: string]: (string);
});

export type TelemetryGetTelemetrySummaryData = {
    limit?: number;
    repoId: string;
    skip?: number;
};

export type TelemetryGetTelemetrySummaryResponse = (TelemetrySummaryPublic);

export type TelemetryGetTelemetryFindingsData = {
    repoId: string;
};

export type TelemetryGetTelemetryFindingsResponse = (Array<DynamicEnrichmentPublic>);

export type TelemetryAnalyzeTelemetryData = {
    repoId: string;
};

export type TelemetryAnalyzeTelemetryResponse = ({
    [key: string]: (string | number);
});

export type TerraformCreateTerraformRootData = {
    requestBody: TerraformRootCreate;
};

export type TerraformCreateTerraformRootResponse = (TerraformRootPublic);

export type TerraformListTerraformRootsData = {
    repoId?: (string | null);
};

export type TerraformListTerraformRootsResponse = (Array<TerraformRootPublic>);

export type TerraformToggleTerraformRootData = {
    enabled: boolean;
    rootId: string;
};

export type TerraformToggleTerraformRootResponse = ({
    [key: string]: (string | boolean);
});

export type TerraformDeleteTerraformRootData = {
    rootId: string;
};

export type TerraformDeleteTerraformRootResponse = (void);

export type TerraformTriggerTerraformScanData = {
    branch?: (string | null);
    rootId: string;
};

export type TerraformTriggerTerraformScanResponse = ({
    [key: string]: (string);
});

export type TerraformListTerraformScansData = {
    rootId: string;
};

export type TerraformListTerraformScansResponse = (Array<TerraformScanPublic>);

export type TerraformListTerraformFindingsData = {
    includeResolved?: boolean;
    rootId: string;
};

export type TerraformListTerraformFindingsResponse = (Array<TerraformFindingPublic>);

export type TerraformListTerraformFilesData = {
    ref?: (string | null);
    rootId: string;
};

export type TerraformListTerraformFilesResponse = (Array<TerraformFilePublic>);

export type TerraformListTerraformFixesData = {
    rootId: string;
};

export type TerraformListTerraformFixesResponse = (Array<TerraformFixPublic>);

export type TerraformTriggerTerraformFixGenerationData = {
    force?: boolean;
    requestBody?: (TerraformFixGenerateRequest | null);
    rootId: string;
};

export type TerraformTriggerTerraformFixGenerationResponse = ({
    [key: string]: (string | number);
});

export type TerraformTriggerTerraformDeliveryData = {
    force?: boolean;
    rootId: string;
};

export type TerraformTriggerTerraformDeliveryResponse = ({
    [key: string]: (string);
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WebhooksGithubWebhookData = {
    xGithubDelivery?: (string | null);
    xGithubEvent?: (string | null);
    xHubSignature256?: (string | null);
};

export type WebhooksGithubWebhookResponse = ({
    [key: string]: (string);
});
