// This file is auto-generated by @hey-api/openapi-ts

export type AIProviderInfo = {
    id: string;
    name: string;
    available: boolean;
    default_model: string;
    models: Array<(string)>;
};

export type AIProvidersPublic = {
    providers: Array<AIProviderInfo>;
};

/**
 * One Ansible file's live source for a project.
 *
 * Ansible files aren't persisted (unlike ``WorkflowFile``); they're fetched
 * from GitHub on demand, so this carries no id or branch — just the path and
 * content, mirroring ``TerraformFilePublic``.
 */
export type AnsibleFilePublic = {
    path: string;
    raw_content: string;
    kind: string;
};

export type AnsibleFindingPublic = {
    id: string;
    scan_id: string;
    rule_id: string;
    rule_slug: string;
    severity: Severity;
    category: Category;
    message: string;
    context?: (string | null);
    status: FindingStatus;
    created_at?: (string | null);
    resolved_at?: (string | null);
    resolution_reason?: (FindingResolutionReason | null);
    fix_id?: (string | null);
    fix_status?: (FixStatus | null);
    ansible_project_id: string;
    file_path: string;
    line_start?: (number | null);
    line_end?: (number | null);
    task_name?: (string | null);
};

export type AnsibleFixGenerateRequest = {
    finding_ids?: (Array<(string)> | null);
};

export type AnsibleFixPublic = {
    id: string;
    file_path: string;
    pr_id?: (string | null);
    llm_provider: LLMProvider;
    llm_model: string;
    status: FixStatus;
    full_content?: (string | null);
    error_message?: (string | null);
    pr_url?: (string | null);
    pr_branch?: (string | null);
    pr_state?: (PullRequestState | null);
    created_at?: (string | null);
    delivered_at?: (string | null);
    ansible_project_id: string;
};

export type AnsibleProjectCreate = {
    repo_id: string;
    root_path: string;
};

export type AnsibleProjectPublic = {
    id: string;
    repo_id: string;
    repo_full_name?: (string | null);
    root_path: string;
    enabled: boolean;
    last_scanned_at?: (string | null);
    last_scanned_head_sha?: (string | null);
    latest_score?: (number | null);
    latest_grade?: (string | null);
    latest_scan_status?: (ScanStatus | null);
    badge_sig?: (string | null);
};

export type AnsibleScanPublic = {
    id: string;
    status: ScanStatus;
    triggered_by: ScanTrigger;
    score?: (number | null);
    grade?: (string | null);
    error_message?: (string | null);
    created_at?: (string | null);
    completed_at?: (string | null);
    branch?: (string | null);
    commit_sha?: (string | null);
    ansible_project_id: string;
    file_count?: (number | null);
};

export type BatchFixRequest = {
    issue_ids?: (Array<(string)> | null);
};

/**
 * The billing page's headline: plan, payment state, and usage.
 *
 * ``tier`` is the purchased plan and ``effective_tier`` is what limits are
 * actually being applied — they differ exactly when a subscription is
 * ``unpaid`` or ``canceled``, and showing both is what lets the UI say "Pro,
 * currently limited to Free" instead of silently misreporting one or other.
 */
export type BillingSubscriptionPublic = {
    id: string;
    tier: UserTier;
    effective_tier: UserTier;
    status: SubscriptionStatus;
    analyses_used: number;
    fixes_used: number;
    repos_used?: number;
    period_start?: (string | null);
    period_end?: (string | null);
    grace_expires_at?: (string | null);
    cancel_at_period_end?: boolean;
    trial_end?: (string | null);
    billing_enabled?: boolean;
};

export type Body_auth_create_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_auth_github_callback = {
    grant_type?: (string | null);
    code: string;
    client_id?: (string | null);
    redirect_uri?: (string | null);
    code_verifier?: (string | null);
};

/**
 * Which axis a rule grades on. Also the directory a .rego file lives in.
 */
export type Category = 'energy' | 'reliability' | 'security' | 'performance' | 'maintainability';

export type CheckoutRequest = {
    tier: UserTier;
};

/**
 * The Stripe-hosted URL the browser must be sent to.
 */
export type CheckoutSessionPublic = {
    url: string;
};

/**
 * Aggregate CI outcome for a PR, from ``check_suite`` webhooks.
 */
export type CIStatus = 'pending' | 'success' | 'failure' | 'none';

export type CloudAccountCreate = {
    org_id: string;
    display_name: string;
    role_arn: string;
    regions?: Array<(string)>;
};

export type CloudAccountPublic = {
    id: string;
    org_id: string;
    provider: CloudProvider;
    display_name: string;
    role_arn?: (string | null);
    external_id: string;
    regions?: Array<(string)>;
    status: CloudAccountStatus;
    last_synced_at?: (string | null);
    latest_score?: (number | null);
    latest_grade?: (string | null);
    latest_scan_status?: (ScanStatus | null);
    badge_sig?: (string | null);
    created_at?: (string | null);
};

export type CloudAccountStatus = 'pending_verification' | 'connected' | 'error' | 'disabled';

export type CloudFindingPublic = {
    id: string;
    scan_id: string;
    rule_id: string;
    rule_slug: string;
    severity: Severity;
    category: Category;
    message: string;
    context?: (string | null);
    status: FindingStatus;
    created_at?: (string | null);
    resolved_at?: (string | null);
    resolution_reason?: (FindingResolutionReason | null);
    cloud_account_id: string;
    resource_type: string;
    resource_id: string;
    region?: (string | null);
};

export type CloudProvider = 'aws';

export type CloudScanPublic = {
    id: string;
    status: ScanStatus;
    triggered_by: ScanTrigger;
    score?: (number | null);
    grade?: (string | null);
    error_message?: (string | null);
    created_at?: (string | null);
    completed_at?: (string | null);
    cloud_account_id: string;
    region?: (string | null);
    resource_count?: number;
};

/**
 * One image build (and optionally its containers) observed in CI.
 *
 * A workflow can build several images, so this is posted once per image
 * rather than once per run — which is exactly why it is not folded into
 * TelemetryPayload.
 */
export type DockerBuildPayload = {
    workflow_run_id: number;
    image_ref?: (string | null);
    dockerfile_path?: (string | null);
    image_size_bytes?: (number | null);
    context_size_bytes?: (number | null);
    build_duration_ms?: (number | null);
    cache_hit_ratio?: (number | null);
    layers?: (Array<{
    [key: string]: unknown;
}> | null);
    containers?: (Array<{
    [key: string]: unknown;
}> | null);
};

/**
 * One measured build, with the findings its measurements produced.
 *
 * ``layers`` and ``containers`` are stored as JSON text (they are
 * collector-shaped and never queried relationally) and decoded here, so the
 * frontend never parses a string out of a typed field.
 */
export type DockerBuildTelemetryPublic = {
    id: string;
    workflow_run_id: number;
    image_ref?: (string | null);
    dockerfile_path?: (string | null);
    image_size_bytes?: (number | null);
    context_size_bytes?: (number | null);
    build_duration_ms?: (number | null);
    cache_hit_ratio?: (number | null);
    layers?: Array<{
        [key: string]: unknown;
    }>;
    containers?: Array<{
        [key: string]: unknown;
    }>;
    collected_at?: (string | null);
    findings?: Array<DockerRuntimeFindingPublic>;
};

/**
 * A Dockerfile or Compose file's live source for a target.
 *
 * Not persisted (mirroring ``TerraformFilePublic``): fetched from GitHub on
 * demand, so it carries no id/branch — just path and content. ``kind`` lets
 * the viewer pick a syntax highlighter without re-deriving it from the name.
 */
export type DockerFilePublic = {
    path: string;
    raw_content: string;
    kind: string;
};

export type DockerFindingPublic = {
    id: string;
    scan_id: string;
    rule_id: string;
    rule_slug: string;
    severity: Severity;
    category: Category;
    message: string;
    context?: (string | null);
    status: FindingStatus;
    created_at?: (string | null);
    resolved_at?: (string | null);
    resolution_reason?: (FindingResolutionReason | null);
    fix_id?: (string | null);
    fix_status?: (FixStatus | null);
    docker_target_id: string;
    file_path: string;
    service_name?: (string | null);
    stage_name?: (string | null);
    line_start?: (number | null);
    line_end?: (number | null);
};

export type DockerFixGenerateRequest = {
    finding_ids?: (Array<(string)> | null);
};

export type DockerFixPublic = {
    id: string;
    file_path: string;
    pr_id?: (string | null);
    llm_provider: LLMProvider;
    llm_model: string;
    status: FixStatus;
    full_content?: (string | null);
    error_message?: (string | null);
    pr_url?: (string | null);
    pr_branch?: (string | null);
    pr_state?: (PullRequestState | null);
    created_at?: (string | null);
    delivered_at?: (string | null);
    docker_target_id: string;
};

/**
 * One ``DockerBuildEnrichment`` dressed for the Runtime tab.
 *
 * The stored row carries only a rule slug; severity, category and title are
 * resolved from the rule catalog here so the tab can sort and colour without
 * a second request. All three are nullable because a Rego rule shipped
 * without a seed entry in ``core/db.py`` still evaluates and still produces
 * enrichments — it just has no catalog row to describe it.
 */
export type DockerRuntimeFindingPublic = {
    id: string;
    telemetry_id: string;
    rule_slug: string;
    rule_title?: (string | null);
    severity?: (Severity | null);
    category?: (Category | null);
    evidence: string;
    recommendation: string;
    created_at?: (string | null);
};

export type DockerRuntimeFixRequest = {
    enrichment_ids: Array<(string)>;
};

export type DockerScanPublic = {
    id: string;
    status: ScanStatus;
    triggered_by: ScanTrigger;
    score?: (number | null);
    grade?: (string | null);
    error_message?: (string | null);
    created_at?: (string | null);
    completed_at?: (string | null);
    branch?: (string | null);
    commit_sha?: (string | null);
    docker_target_id: string;
    file_count?: (number | null);
};

export type DockerTargetCreate = {
    repo_id: string;
    root_path?: string;
};

export type DockerTargetPublic = {
    id: string;
    repo_id: string;
    repo_full_name?: (string | null);
    root_path: string;
    enabled: boolean;
    last_scanned_at?: (string | null);
    last_scanned_head_sha?: (string | null);
    latest_score?: (number | null);
    latest_grade?: (string | null);
    latest_scan_status?: (ScanStatus | null);
    badge_sig?: (string | null);
};

/**
 * Lifecycle of the dynamic-analysis enrichment for a ``completed``-phase
 * telemetry run.
 *
 * Distinct from ``TelemetryPhase`` (an ingest category — ``started`` and
 * ``completed`` are separate rows): this tracks the worker that turns a
 * completed run's metrics into persisted ``DynamicEnrichment`` findings.
 */
export type DynamicAnalysisStatus = 'queued' | 'running' | 'enriched' | 'failed';

/**
 * A runtime-telemetry finding, exposed for the frontend.
 *
 * Deliberately thinner than ``WorkflowFindingPublic``: enrichments carry no severity,
 * category, status/lifecycle, line numbers, or fix linkage, so they are
 * presented as their own "Runtime findings" class rather than merged into the
 * static issue list.
 */
export type DynamicEnrichmentPublic = {
    id: string;
    telemetry_run_id: string;
    workflow_run_id?: (number | null);
    rule_slug: string;
    evidence: string;
    recommendation: string;
    created_at?: (string | null);
};

/**
 * Which analysis engine produced something.
 *
 * The one name for an engine across the whole system: usage records tag
 * themselves with it, the dashboard overview keys its stat blocks by it, and
 * ``services/engines.EngineSpec`` is looked up by it. There used to be three
 * of these enums disagreeing about whether the first one is called ``ci`` or
 * ``workflow``; it is ``workflow``, after the ``WorkflowFile`` rows it scans.
 *
 * Not the same axis as :class:`RuleDomain`, which names a Rego package — the
 * mapping is many-to-one and lives in :data:`ENGINE_OF_DOMAIN`.
 */
export type Engine = 'workflow' | 'terraform' | 'ansible' | 'docker' | 'cloud' | 'telemetry';

/**
 * How much of what could be scanned actually has been.
 *
 * ``enabled`` means different things per engine — a bool column for Docker
 * and Terraform targets, ``CloudAccountStatus.connected`` for a cloud
 * account. The CI engine's target is a ``WorkflowFile``, which has no enable
 * switch at all, so there ``enabled == total``.
 */
export type EngineCoverageStat = {
    total: number;
    enabled: number;
    scanned: number;
    never_scanned: number;
    latest_scan_failed: number;
};

export type EngineFindingStat = {
    open: number;
    resolved: number;
    critical_open: number;
    by_severity: Array<SeverityStat>;
    by_category: Array<FindingCategoryStat>;
};

/**
 * Open findings bucketed by the state of the fix addressing them.
 *
 * ``unfixed`` mirrors ``list_issues(unfixed=True)``: no fix row at all, or a
 * fix in one of the rejected/superseded states. The buckets are disjoint and
 * sum to ``EngineFindingStat.open``.
 */
export type EngineFixPipelineStat = {
    unfixed: number;
    in_progress: number;
    ready: number;
    delivered: number;
    landed: number;
    failed: number;
};

export type EngineFreshnessStat = {
    last_completed_scan_at: (string | null);
    last_scan_at: (string | null);
};

export type EngineOverview = {
    engine: Engine;
    section: OverviewSection;
    label: string;
    coverage: EngineCoverageStat;
    freshness: EngineFreshnessStat;
    score: EngineScoreStat;
    findings: EngineFindingStat;
    fixes: (EngineFixPipelineStat | null);
    top_rules: Array<TopRuleStat>;
};

/**
 * Average of each target's latest *completed* scan score.
 *
 * A target whose latest scan failed keeps the score of its last good scan —
 * the same rule ``api/mappers/base.latest_completed_scan`` applies per
 * target, so a grade here always matches the one that engine's own list
 * endpoint reports.
 */
export type EngineScoreStat = {
    avg_score: (number | null);
    grade: (string | null);
    scored_targets: number;
    by_grade: Array<GradeStat>;
};

export type ExternalRepositoryCreate = {
    full_name: string;
    installation_id?: (number | null);
};

export type FindingCategoryStat = {
    category: Category;
    open: number;
    resolved: number;
    critical_open: number;
};

/**
 * Why a finding stopped being open.
 *
 * An attribute of the ``resolved`` state, not a state of its own. The union of
 * what the engines can observe: the first two are available to all of them,
 * the rest need a file or a pull request and so only arise on engines that
 * have one.
 */
export type FindingResolutionReason = 'no_longer_detected' | 'target_removed' | 'file_removed' | 'merged' | 'branch_deleted';

/**
 * Derived lifecycle of a rule violation, on any engine.
 *
 * For CI-workflow findings this column is computed by a database trigger from
 * ``ignored_at``, ``resolved_at`` and ``fix_id`` (migrations ``0022``/``0026``,
 * renamed in ``0053``); ``ignored`` takes precedence, so a user-dismissed
 * violation stays muted regardless of fix or resolve activity. The other
 * engines set it directly through ``FindingMachine``.
 *
 * ``fix_in_progress`` arrived with the merge of the old ``FindingStatus``: only
 * the CI engine reaches it today, because only its findings carry a ``fix_id``
 * — the other engines key a fix on ``(target, file_path)`` instead. It is
 * declared here rather than in a CI-only enum because the state is about the
 * finding, not about which engine found it.
 */
export type FindingStatus = 'open' | 'fix_in_progress' | 'resolved' | 'ignored';

export type FixDeliveryMode = 'pr' | 'comment' | 'disabled';

/**
 * The findings one fix set out to resolve, as the fix detail view lists them.
 */
export type FixFindingSummary = {
    id: string;
    rule_slug?: (string | null);
    severity?: (Severity | null);
    category?: (Category | null);
    message?: (string | null);
    line_start?: (number | null);
    line_end?: (number | null);
};

export type FixStatus = 'pending' | 'generating' | 'ready' | 'delivering' | 'delivered' | 'failed' | 'rejected_by_user' | 'superseded_by_closed_pr' | 'superseded_by_deleted_file' | 'landed' | 'no_op';

/**
 * How many scan targets currently hold this grade.
 *
 * Emitted for every rung of ``services.scoring.GRADE_LADDER`` in order, best
 * first, plus any grade found in the data that isn't on the ladder — grades
 * are free-form ``VARCHAR(8)``, so a row written before a ladder change must
 * still be counted rather than silently dropped.
 */
export type GradeStat = {
    grade: string;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InstallationSyncRequest = {
    code: string;
    redirect_uri?: (string | null);
};

export type InvoicePublic = {
    id: string;
    stripe_invoice_id: string;
    number?: (string | null);
    status: InvoiceStatus;
    amount_due_cents: number;
    amount_paid_cents: number;
    currency: string;
    hosted_invoice_url?: (string | null);
    invoice_pdf?: (string | null);
    period_start?: (string | null);
    period_end?: (string | null);
    paid_at?: (string | null);
    created_at?: (string | null);
};

/**
 * Mirrors Stripe's invoice statuses, minus ``deleted`` (drafts only).
 */
export type InvoiceStatus = 'draft' | 'open' | 'paid' | 'void' | 'uncollectible';

export type LLMProvider = 'openai' | 'anthropic' | 'gemini' | 'ollama';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrganizationPublic = {
    id: string;
    name: string;
    tier: UserTier;
    default_llm_provider?: (LLMProvider | null);
    default_llm_model?: (string | null);
    fix_delivery_mode: FixDeliveryMode;
    created_at?: (string | null);
};

export type OrganizationUpdate = {
    default_llm_provider?: (LLMProvider | null);
    default_llm_model?: (string | null);
};

/**
 * Every meter an organization can be refused on.
 */
export type OrgQuotasPublic = {
    analyses: QuotaPublic;
    fixes: QuotaPublic;
    repos: QuotaPublic;
};

export type OssApplicationCreate = {
    repo_url: string;
    license_name: string;
    justification: string;
};

export type OssApplicationPublic = {
    id: string;
    user_id: string;
    repo_url: string;
    license_name: string;
    justification: string;
    status: OssApplicationStatus;
    review_note?: (string | null);
    reviewed_at?: (string | null);
    created_at?: (string | null);
};

export type OssApplicationReview = {
    approve: boolean;
    review_note?: (string | null);
};

/**
 * Review state of a request for the granted open-source plan.
 */
export type OssApplicationStatus = 'pending' | 'approved' | 'rejected' | 'withdrawn';

export type OverviewPublic = {
    generated_at: string;
    totals: OverviewTotals;
    engines: Array<EngineOverview>;
};

/**
 * Which collapsible dashboard section an engine renders under.
 *
 * Four engines, three sections: the Infrastructure page already shows
 * Terraform and cloud posture as sibling tabs, so the dashboard groups them
 * the same way rather than inventing a fourth top-level heading.
 */
export type OverviewSection = 'ci' | 'docker' | 'infra';

/**
 * All-engine roll-up for the dashboard's summary header.
 *
 * ``avg_score`` is the unweighted mean of the per-engine averages that
 * exist, not of every target: averaging targets directly would let a repo
 * with forty workflow files drown out a failing cloud posture.
 */
export type OverviewTotals = {
    targets: number;
    enabled_targets: number;
    never_scanned_targets: number;
    open_findings: number;
    resolved_findings: number;
    critical_open: number;
    avg_score: (number | null);
    grade: (string | null);
    by_severity: Array<SeverityStat>;
    by_category: Array<FindingCategoryStat>;
    engines_with_data: number;
};

/**
 * The address to send a reset link to.
 *
 * A body rather than a path segment: an email in a URL lands in every access
 * log and needs percent-encoding that callers were not doing.
 */
export type PasswordRecovery = {
    email: string;
};

/**
 * Where a plan purchase went — a payment page, or the plan itself.
 *
 * An account with no live subscription is sent to Stripe Checkout and gets a
 * ``url`` to visit. An account that already has one changes that
 * subscription in place instead, so there is no page: ``tier`` is what it is
 * now on and ``effective_at`` when, which is ``None`` for an upgrade
 * (immediately) and the renewal date for a downgrade, since a downgrade
 * leaves the plan already paid for running to the end of the period.
 *
 * Exactly one side is ever filled in, and ``url`` is the one to check: a
 * client that has a URL should navigate, and otherwise report the change.
 */
export type PlanChangePublic = {
    url?: (string | null);
    tier?: (UserTier | null);
    effective_at?: (string | null);
};

/**
 * ``None`` means unlimited, at every layer up to the UI.
 */
export type PlanLimitsPublic = {
    analyses?: (number | null);
    fixes?: (number | null);
    repos?: (number | null);
};

export type PlanPublic = {
    tier: UserTier;
    name: string;
    price_cents: number;
    price_display: string;
    tagline: string;
    limits: PlanLimitsPublic;
    auto_fix: boolean;
    public_repos_only: boolean;
    is_purchasable: boolean;
    features?: Array<(string)>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type PullRequestPublic = {
    id: string;
    repo_id: string;
    pr_branch: string;
    pr_url?: (string | null);
    pr_state?: (PullRequestState | null);
    ci_status?: (CIStatus | null);
    review_decision?: (ReviewDecision | null);
    mergeable_state?: (string | null);
    externally_modified?: boolean;
    comment_url?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type PullRequestState = 'open' | 'draft' | 'merged' | 'closed';

/**
 * One meter's standing for an organization, and the refusal it would draw.
 *
 * ``exhausted_reason`` is the whole point: it is the *exact* sentence
 * ``enforce_quota`` puts in its 402, or ``None`` when the next unit would go
 * through. A client greys a button out on the string alone, and the tooltip
 * it shows is then the error it prevented rather than a paraphrase of it —
 * the same discipline ``state_machines/engine_target.REASONS`` keeps for the
 * activity refusals.
 */
export type QuotaPublic = {
    meter: string;
    limit?: (number | null);
    used?: number;
    remaining?: (number | null);
    resets_at?: (string | null);
    exhausted_reason?: (string | null);
};

/**
 * A repo's open-finding counts and severity-weighted grade for one category.
 *
 * ``score``/``grade`` are ``None`` when the repo has no overall grade yet
 * (e.g. no completed scan). See ``RepoFindingStats`` for how categories
 * are grouped per repo.
 */
export type RepoCategoryStat = {
    category: Category;
    open: number;
    critical_open: number;
    score?: (number | null);
    grade?: (string | null);
};

/**
 * One engine's average grade for a repository.
 *
 * Only engines that have actually scored the repo appear. An engine that has
 * never run has no entry, which is a different statement from a bad grade and
 * is what lets a page render "—" rather than an invented letter.
 */
export type RepoEngineGrade = {
    engine: Engine;
    score: number;
    grade: string;
};

/**
 * Per-repo finding breakdown — powers the dashboard's category health star
 * diagram. Only populated on the unscoped (all-repos) stats call;
 * meaningless once already filtered to a single ``repo_id``.
 *
 * ``score``/``grade`` here are the repo's own overall grade (same values as
 * ``RepositoryPublic.avg_score``/``grade``), repeated so the frontend
 * doesn't need a second lookup to size the radar's "no findings" fallback.
 * Each entry in ``categories`` covers every ``Category``, including
 * categories with zero open findings, so their scores average out to exactly
 * the repo's overall score (see ``compute_category_scores``).
 */
export type RepoFindingStats = {
    repo_id: string;
    score?: (number | null);
    grade?: (string | null);
    categories?: Array<RepoCategoryStat>;
};

export type RepositoryPublic = {
    id: string;
    org_id: string;
    full_name: string;
    enabled: boolean;
    is_accessible?: boolean;
    is_external?: boolean;
    is_private?: boolean;
    default_branch: string;
    auto_fix_enabled?: boolean;
    tier?: (UserTier | null);
    badge_sig?: (string | null);
    created_at?: (string | null);
    latest_scan_status?: (ScanStatus | null);
    avg_score?: (number | null);
    grade?: (string | null);
    engine_grades?: Array<RepoEngineGrade>;
};

/**
 * The two switches a repository owner can flip.
 *
 * Both are optional: a ``PATCH`` naming only one leaves the other alone.
 * Enabling either is quota-checked, which is why they are not a blanket
 * "update the repository" body — nothing else about a repo is user-writable.
 */
export type RepositoryUpdate = {
    enabled?: (boolean | null);
    auto_fix_enabled?: (boolean | null);
};

/**
 * Latest human review decision for a PR, from ``pull_request_review``.
 */
export type ReviewDecision = 'approved' | 'changes_requested' | 'review_required';

export type RulePublic = {
    id: string;
    slug: string;
    category: Category;
    severity: Severity;
    title: string;
    description: string;
    enabled: boolean;
};

/**
 * A rule's catalog-wide on/off switch.
 */
export type RuleUpdate = {
    enabled?: (boolean | null);
};

export type SamplePayload = {
    workflow_run_id: number;
    cpu_percent?: (number | null);
    ram_used_mb?: (number | null);
    disk_used_gb?: (number | null);
    net_bytes_sent?: (number | null);
    net_bytes_recv?: (number | null);
    top_processes?: (Array<{
    [key: string]: unknown;
}> | null);
};

/**
 * Lifecycle of one engine's run over one target.
 *
 * Shared by every scan table. There used to be a second, identical enum called
 * ``ScanStatus`` for the CI engine alone, differing in exactly one member:
 * it spelled the empty case ``no_workflows`` where this one says
 * ``no_targets``. That is workflow-specific vocabulary for a case every engine
 * has — no ``.tf`` files under this root, no resources of the scanned types in
 * this account, no workflow files in this repository — so the general name
 * won and migration 0053 rewrote the rows.
 */
export type ScanStatus = 'queued' | 'running' | 'completed' | 'failed' | 'no_targets';

/**
 * The mutable part of a registered scan target.
 *
 * Every engine enables and disables its target the same way, so one body
 * serves all of them rather than three identical copies. Optional so a
 * ``PATCH`` that omits the field leaves it alone.
 */
export type ScanTargetUpdate = {
    enabled?: (boolean | null);
};

export type ScanTrigger = 'webhook_push' | 'webhook_workflow_run' | 'polled_push' | 'manual' | 'scheduled' | 'release' | 'code_scanning';

/**
 * How bad a rule violation is. Shared by every engine's findings.
 */
export type Severity = 'critical' | 'high' | 'medium' | 'low' | 'info';

/**
 * Open/resolved finding counts for one severity.
 *
 * Emitted for every ``Severity`` including zeros, so the frontend can
 * render a fixed-segment severity bar without gap logic.
 */
export type SeverityStat = {
    severity: Severity;
    open: number;
    resolved: number;
};

/**
 * The wire shape of one server-sent event.
 *
 * Every event is a flat JSON object: an ``event`` discriminant plus whatever
 * the emitting factory in ``services/events/schemas.py`` put beside it. That
 * payload was a bare ``dict[str, Any]`` and never reached OpenAPI, so the
 * frontend read it by hand — ``data.grade as string | undefined``, forty times
 * over in ``hooks/useRepoEvents.ts``. A renamed field broke silently at
 * runtime, in a browser, with nothing to catch it.
 *
 * Declaring it here puts the field names in the generated client, which turns
 * that class of break into a TypeScript error.
 *
 * Every field but ``event`` is optional, and deliberately so: this is a union
 * of what ~30 distinct signals carry, not a claim that any one of them carries
 * all of it. Which fields a given signal actually populates is documented on
 * its factory function. The alternative — a discriminated union with one model
 * per signal — buys per-signal precision at the cost of thirty-odd models to
 * keep in step with their factories, and the consumer switches on ``event``
 * anyway.
 */
export type SSEEventPublic = {
    event: SSESignal;
    org_id?: (string | null);
    repo_id?: (string | null);
    repo_ids?: (Array<(string)> | null);
    analysis_id?: (string | null);
    fix_id?: (string | null);
    fix_ids?: (Array<(string)> | null);
    issue_ids?: (Array<(string)> | null);
    telemetry_run_id?: (string | null);
    installation_id?: (number | null);
    branch?: (string | null);
    trigger?: (string | null);
    score?: (number | null);
    grade?: (string | null);
    issues_count?: (number | null);
    error?: (string | null);
    pr_url?: (string | null);
    pr_branch?: (string | null);
    org_name?: (string | null);
    repo_count?: (number | null);
    repos_disabled?: (number | null);
    enabled?: (boolean | null);
    tier?: (string | null);
    status?: (string | null);
    meter?: (string | null);
    message?: (string | null);
};

export type SSESignal = 'analysis.queued' | 'analysis.started' | 'analysis.completed' | 'analysis.failed' | 'analysis.skipped' | 'analysis.no_workflows' | 'fix.skipped' | 'fix.pending' | 'fix.generating' | 'fix.ready' | 'fix.delivering' | 'fix.delivered' | 'fix.failed' | 'fix.rejected' | 'fix.landed' | 'pr.opened' | 'pr.updated' | 'pr.closed' | 'pr.merged' | 'installation.syncing' | 'installation.synced' | 'installation.created' | 'installation.deleted' | 'installation.suspended' | 'installation.unsuspended' | 'installation.updated' | 'repository.added' | 'repository.disabled' | 'repository.toggled' | 'repository.action_pr_opened' | 'repository.suspended' | 'repository.archived' | 'repository.inaccessible' | 'repository.restored' | 'dynamic.queued' | 'dynamic.running' | 'dynamic.enriched' | 'dynamic.failed' | 'analysis.quota_exceeded' | 'subscription.activated' | 'subscription.past_due' | 'subscription.unpaid' | 'subscription.canceled' | 'subscription.updated';

/**
 * Lifecycle of a ``BillingSubscription`` — see ``BillingSubscriptionMachine``.
 *
 * Orthogonal to ``UserTier``: the tier says *what was bought*, this says
 * *whether it is currently being paid for*. The combination is resolved by
 * ``services/billing/lifecycle.effective_tier``, which is the only thing
 * quota enforcement reads.
 *
 * ``past_due`` deliberately keeps full paid service — it is the grace window,
 * not a punishment. Only ``unpaid`` (grace expired) and ``canceled`` fall
 * back to Free limits, and neither ever removes data.
 */
export type SubscriptionStatus = 'incomplete' | 'trialing' | 'active' | 'past_due' | 'unpaid' | 'pending_cancellation' | 'canceled';

/**
 * Averaged telemetry across a repo's runs.
 *
 * Sample-derived fields are averaged over ``TelemetryMetricSample`` rows;
 * run-derived fields (``avg_ram_percent``, ``avg_vcpus``) come from the
 * per-run ``metrics``/``runner_specs`` JSON. Any field is ``None`` when no
 * data supports it.
 */
export type TelemetryAveragePublic = {
    run_count?: number;
    sample_count?: number;
    avg_cpu_percent?: (number | null);
    avg_ram_used_mb?: (number | null);
    avg_ram_percent?: (number | null);
    avg_disk_used_gb?: (number | null);
    avg_net_bytes_sent?: (number | null);
    avg_net_bytes_recv?: (number | null);
    avg_vcpus?: (number | null);
};

export type TelemetryPayload = {
    workflow_run_id: number;
    branch?: string;
    commit_sha?: string;
    workflow_name?: string;
    runner_specs?: {
        [key: string]: unknown;
    };
    metrics?: {
        [key: string]: unknown;
    };
    phase?: TelemetryPhase;
};

export type TelemetryPhase = 'started' | 'completed';

export type TelemetryRunPublic = {
    id: string;
    workflow_run_id: number;
    phase?: (TelemetryPhase | null);
    dynamic_status?: (DynamicAnalysisStatus | null);
    runner_specs?: {
        [key: string]: unknown;
    };
    metrics?: {
        [key: string]: unknown;
    };
    collected_at?: (string | null);
    enrichments?: Array<DynamicEnrichmentPublic>;
};

export type TelemetrySummaryPublic = {
    average: TelemetryAveragePublic;
    runs?: Array<TelemetryRunPublic>;
};

/**
 * A ``.tf`` file's live source for a Terraform root.
 *
 * Terraform files aren't persisted (unlike ``WorkflowFile``); they're fetched
 * from GitHub on demand, so this carries no id/branch — just the path and
 * content, mirroring the shape of ``WorkflowFilePublic``.
 */
export type TerraformFilePublic = {
    path: string;
    raw_content: string;
};

export type TerraformFindingPublic = {
    id: string;
    scan_id: string;
    rule_id: string;
    rule_slug: string;
    severity: Severity;
    category: Category;
    message: string;
    context?: (string | null);
    status: FindingStatus;
    created_at?: (string | null);
    resolved_at?: (string | null);
    resolution_reason?: (FindingResolutionReason | null);
    fix_id?: (string | null);
    fix_status?: (FixStatus | null);
    terraform_root_id: string;
    resource_address?: (string | null);
    file_path: string;
    line_start?: (number | null);
    line_end?: (number | null);
    module_path?: (string | null);
    terraform_address?: (string | null);
};

export type TerraformFixGenerateRequest = {
    finding_ids?: (Array<(string)> | null);
};

export type TerraformFixPublic = {
    id: string;
    file_path: string;
    pr_id?: (string | null);
    llm_provider: LLMProvider;
    llm_model: string;
    status: FixStatus;
    full_content?: (string | null);
    error_message?: (string | null);
    pr_url?: (string | null);
    pr_branch?: (string | null);
    pr_state?: (PullRequestState | null);
    created_at?: (string | null);
    delivered_at?: (string | null);
    terraform_root_id: string;
};

export type TerraformRootCreate = {
    repo_id: string;
    root_path: string;
};

export type TerraformRootPublic = {
    id: string;
    repo_id: string;
    repo_full_name?: (string | null);
    root_path: string;
    enabled: boolean;
    last_scanned_at?: (string | null);
    last_scanned_head_sha?: (string | null);
    latest_score?: (number | null);
    latest_grade?: (string | null);
    latest_scan_status?: (ScanStatus | null);
    badge_sig?: (string | null);
};

export type TerraformScanPublic = {
    id: string;
    status: ScanStatus;
    triggered_by: ScanTrigger;
    score?: (number | null);
    grade?: (string | null);
    error_message?: (string | null);
    created_at?: (string | null);
    completed_at?: (string | null);
    branch?: (string | null);
    commit_sha?: (string | null);
    terraform_root_id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * A rule ranked by how many open findings it accounts for.
 */
export type TopRuleStat = {
    rule_id: string;
    slug: string;
    title: string;
    severity: Severity;
    category: Category;
    open: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * How much of one meter a single engine accounted for this period.
 */
export type UsageBreakdownPublic = {
    meter: UsageMeter;
    engine: UsageEngine;
    quantity: number;
};

/**
 * Which engine produced a usage record, plus one non-engine sentinel.
 *
 * Every one of these debits the same shared pool; the tag exists so a user
 * can see *where* their allowance went, and so tests can assert that each
 * engine is actually metered.
 *
 * Its engine members are :class:`Engine`'s, spelled out rather than generated
 * so the persisted values stay greppable — ``_ENGINE_MEMBERS_MATCH`` below
 * fails at import if the two ever drift.
 */
export type UsageEngine = 'workflow' | 'terraform' | 'ansible' | 'docker' | 'cloud' | 'telemetry' | 'carryover';

/**
 * Which allowance a usage record draws down.
 *
 * ``repos`` is absent on purpose: it is a live capacity count (how many
 * repositories are enabled right now), not something consumed over time, so
 * it is measured by querying rather than by ledger entries.
 */
export type UsageMeter = 'analyses' | 'fixes';

/**
 * Per-meter usage with the engine split behind it.
 *
 * The breakdown is what answers "why am I at 90%" — before the ledger there
 * was no way to tell a user that their Terraform roots, not their workflows,
 * were spending the allowance.
 */
export type UsagePublic = {
    period_start?: (string | null);
    period_end?: (string | null);
    analyses_used?: number;
    fixes_used?: number;
    repos_used?: number;
    limits: PlanLimitsPublic;
    breakdown?: Array<UsageBreakdownPublic>;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    github_username?: (string | null);
    tier?: UserTier;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserTier = 'free' | 'starter' | 'pro' | 'ultimate' | 'open_source';

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * What the API is running, for the dashboard footer to compare against.
 *
 * The dashboard and the API are promoted through different platforms —
 * Cloudflare Workers and Coolify — so the dashboard cannot infer the API's
 * version from its own. Reporting it here is what makes a half-finished
 * promotion visible instead of showing up later as a confusing 422.
 */
export type VersionInfo = {
    version: string;
    environment: string;
};

export type WorkflowFilePublic = {
    id: string;
    path: string;
    branch?: (string | null);
    raw_content?: (string | null);
    source_commit_sha?: (string | null);
    fetched_at?: (string | null);
};

/**
 * A rule violation in a workflow file.
 */
export type WorkflowFindingPublic = {
    id: string;
    scan_id: string;
    rule_id: string;
    rule_slug: string;
    severity: Severity;
    category: Category;
    message: string;
    context?: (string | null);
    status: FindingStatus;
    created_at?: (string | null);
    resolved_at?: (string | null);
    resolution_reason?: (FindingResolutionReason | null);
    fix_id?: (string | null);
    fix_status?: (FixStatus | null);
    file_path?: (string | null);
    line_start?: (number | null);
    line_end?: (number | null);
    needs_manual_work?: boolean;
    manual_work_note?: (string | null);
};

/**
 * Exact finding counts, computed by SQL aggregation rather than fetched and
 * counted client-side — unaffected by any page's ``skip``/``limit``.
 */
export type WorkflowFindingStatsPublic = {
    total_open: number;
    total_resolved: number;
    critical_open: number;
    by_category: Array<FindingCategoryStat>;
    by_repo?: Array<RepoFindingStats>;
};

/**
 * An LLM rewrite of one workflow file.
 */
export type WorkflowFixPublic = {
    id: string;
    file_path: string;
    pr_id?: (string | null);
    llm_provider: LLMProvider;
    llm_model: string;
    status: FixStatus;
    full_content?: (string | null);
    error_message?: (string | null);
    pr_url?: (string | null);
    pr_branch?: (string | null);
    pr_state?: (PullRequestState | null);
    created_at?: (string | null);
    delivered_at?: (string | null);
    workflow_file_id: string;
    repo_id?: (string | null);
    base_content?: (string | null);
    comment_url?: (string | null);
    findings?: Array<FixFindingSummary>;
};

/**
 * One static-analysis run over a repository's workflow files.
 */
export type WorkflowScanPublic = {
    id: string;
    status: ScanStatus;
    triggered_by: ScanTrigger;
    score?: (number | null);
    grade?: (string | null);
    error_message?: (string | null);
    created_at?: (string | null);
    completed_at?: (string | null);
    branch?: (string | null);
    commit_sha?: (string | null);
    repo_id: string;
    workflow_file_id?: (string | null);
    file_path?: (string | null);
    repo_full_name?: (string | null);
    content_hash: string;
};

/**
 * What a manual "sync from GitHub" run changed, for the toast in the UI.
 *
 * ``head_sha`` is None when the branch head could not be resolved, in which
 * case the sync read a mutable ref and reconciled nothing it wasn't sure of.
 */
export type WorkflowSyncSummary = {
    branch: string;
    head_sha?: (string | null);
    added?: number;
    updated?: number;
    unchanged?: number;
    restored?: number;
    deleted?: number;
    skipped_stale?: number;
};

export type AnsibleCreateProjectData = {
    requestBody: AnsibleProjectCreate;
};

export type AnsibleCreateProjectResponse = (AnsibleProjectPublic);

export type AnsibleListProjectsData = {
    repoId?: (string | null);
};

export type AnsibleListProjectsResponse = (Array<AnsibleProjectPublic>);

export type AnsibleUpdateProjectData = {
    projectId: string;
    requestBody: ScanTargetUpdate;
};

export type AnsibleUpdateProjectResponse = (AnsibleProjectPublic);

export type AnsibleDeleteProjectData = {
    projectId: string;
};

export type AnsibleDeleteProjectResponse = (void);

export type AnsibleTriggerScanData = {
    branch?: (string | null);
    projectId: string;
};

export type AnsibleTriggerScanResponse = ({
    [key: string]: (string);
});

export type AnsibleListScansData = {
    projectId: string;
};

export type AnsibleListScansResponse = (Array<AnsibleScanPublic>);

export type AnsibleListFindingsData = {
    includeResolved?: boolean;
    projectId: string;
};

export type AnsibleListFindingsResponse = (Array<AnsibleFindingPublic>);

export type AnsibleGetFindingData = {
    ansibleFindingId: string;
};

export type AnsibleGetFindingResponse = (AnsibleFindingPublic);

export type AnsibleIgnoreFindingData = {
    ansibleFindingId: string;
};

export type AnsibleIgnoreFindingResponse = (AnsibleFindingPublic);

export type AnsibleUnignoreFindingData = {
    ansibleFindingId: string;
};

export type AnsibleUnignoreFindingResponse = (AnsibleFindingPublic);

export type AnsibleListFilesData = {
    projectId: string;
    ref?: (string | null);
};

export type AnsibleListFilesResponse = (Array<AnsibleFilePublic>);

export type AnsibleListRepositoryFixesData = {
    repoId: string;
};

export type AnsibleListRepositoryFixesResponse = (Array<AnsibleFixPublic>);

export type AnsibleListFixesData = {
    projectId: string;
};

export type AnsibleListFixesResponse = (Array<AnsibleFixPublic>);

export type AnsibleGenerateFixesData = {
    force?: boolean;
    projectId: string;
    requestBody?: (AnsibleFixGenerateRequest | null);
};

export type AnsibleGenerateFixesResponse = ({
    [key: string]: (string | number);
});

export type AnsibleDeliverFixesData = {
    force?: boolean;
    projectId: string;
};

export type AnsibleDeliverFixesResponse = ({
    [key: string]: (string);
});

export type AnsibleGetSarifData = {
    authorization?: (string | null);
};

export type AnsibleGetSarifResponse = ({
    [key: string]: unknown;
});

export type AnsibleTriggerScansForCodeScanningData = {
    authorization?: (string | null);
    branch?: (string | null);
};

export type AnsibleTriggerScansForCodeScanningResponse = ({
    [key: string]: (string);
});

export type AuthGithubCallbackData = {
    formData: Body_auth_github_callback;
};

export type AuthGithubCallbackResponse = (Token);

export type AuthCreateTokenData = {
    formData: Body_auth_create_token;
};

export type AuthCreateTokenResponse = (Token);

export type AuthVerifyTokenResponse = (UserPublic);

export type AuthRecoverPasswordData = {
    requestBody: PasswordRecovery;
};

export type AuthRecoverPasswordResponse = (Message);

export type AuthResetPasswordData = {
    requestBody: NewPassword;
};

export type AuthResetPasswordResponse = (Message);

export type AuthRegisterUserData = {
    requestBody: UserRegister;
};

export type AuthRegisterUserResponse = (UserPublic);

export type BadgesGetBadgeData = {
    branch: string;
    owner: string;
    repo: string;
    sig?: (string | null);
};

export type BadgesGetBadgeResponse = (unknown);

export type BadgesGetBadgeJsonData = {
    branch: string;
    owner: string;
    repo: string;
    sig?: (string | null);
};

export type BadgesGetBadgeJsonResponse = ({
    [key: string]: unknown;
});

export type BadgesGetTerraformRootBadgeData = {
    rootId: string;
    sig?: (string | null);
};

export type BadgesGetTerraformRootBadgeResponse = (unknown);

export type BadgesGetTerraformRootBadgeJsonData = {
    rootId: string;
    sig?: (string | null);
};

export type BadgesGetTerraformRootBadgeJsonResponse = ({
    [key: string]: unknown;
});

export type BadgesGetAnsibleProjectBadgeData = {
    projectId: string;
    sig?: (string | null);
};

export type BadgesGetAnsibleProjectBadgeResponse = (unknown);

export type BadgesGetAnsibleProjectBadgeJsonData = {
    projectId: string;
    sig?: (string | null);
};

export type BadgesGetAnsibleProjectBadgeJsonResponse = ({
    [key: string]: unknown;
});

export type BadgesGetDockerTargetBadgeData = {
    sig?: (string | null);
    targetId: string;
};

export type BadgesGetDockerTargetBadgeResponse = (unknown);

export type BadgesGetDockerTargetBadgeJsonData = {
    sig?: (string | null);
    targetId: string;
};

export type BadgesGetDockerTargetBadgeJsonResponse = ({
    [key: string]: unknown;
});

export type BadgesGetCloudAccountBadgeData = {
    accountId: string;
    sig?: (string | null);
};

export type BadgesGetCloudAccountBadgeResponse = (unknown);

export type BadgesGetCloudAccountBadgeJsonData = {
    accountId: string;
    sig?: (string | null);
};

export type BadgesGetCloudAccountBadgeJsonResponse = ({
    [key: string]: unknown;
});

export type BillingListPlansResponse = (Array<PlanPublic>);

export type BillingGetSubscriptionResponse = (BillingSubscriptionPublic);

export type BillingGetUsageResponse = (UsagePublic);

export type BillingGetOrgQuotasData = {
    orgId: string;
};

export type BillingGetOrgQuotasResponse = (OrgQuotasPublic);

export type BillingGetTierLimitsResponse = ({
    [key: string]: unknown;
});

export type BillingListInvoicesResponse = (Array<InvoicePublic>);

export type BillingCreateCheckoutSessionData = {
    requestBody: CheckoutRequest;
};

export type BillingCreateCheckoutSessionResponse = (PlanChangePublic);

export type BillingCreatePortalSessionResponse = (CheckoutSessionPublic);

export type BillingListOssApplicationsResponse = (Array<OssApplicationPublic>);

export type BillingCreateOssApplicationData = {
    requestBody: OssApplicationCreate;
};

export type BillingCreateOssApplicationResponse = (OssApplicationPublic);

export type BillingListAllOssApplicationsData = {
    status?: (OssApplicationStatus | null);
};

export type BillingListAllOssApplicationsResponse = (Array<OssApplicationPublic>);

export type BillingReviewOssApplicationData = {
    applicationId: string;
    requestBody: OssApplicationReview;
};

export type BillingReviewOssApplicationResponse = (OssApplicationPublic);

export type CloudCreateAccountData = {
    requestBody: CloudAccountCreate;
};

export type CloudCreateAccountResponse = (CloudAccountPublic);

export type CloudListAccountsData = {
    orgId?: (string | null);
};

export type CloudListAccountsResponse = (Array<CloudAccountPublic>);

export type CloudUpdateAccountData = {
    accountId: string;
    requestBody: ScanTargetUpdate;
};

export type CloudUpdateAccountResponse = (CloudAccountPublic);

export type CloudDeleteAccountData = {
    accountId: string;
};

export type CloudDeleteAccountResponse = (void);

export type CloudTriggerScanData = {
    accountId: string;
};

export type CloudTriggerScanResponse = ({
    [key: string]: (string);
});

export type CloudListScansData = {
    accountId: string;
};

export type CloudListScansResponse = (Array<CloudScanPublic>);

export type CloudListFindingsData = {
    accountId: string;
    includeResolved?: boolean;
};

export type CloudListFindingsResponse = (Array<CloudFindingPublic>);

export type CloudGetFindingData = {
    cloudFindingId: string;
};

export type CloudGetFindingResponse = (CloudFindingPublic);

export type CloudIgnoreFindingData = {
    cloudFindingId: string;
};

export type CloudIgnoreFindingResponse = (CloudFindingPublic);

export type CloudUnignoreFindingData = {
    cloudFindingId: string;
};

export type CloudUnignoreFindingResponse = (CloudFindingPublic);

export type DockerCreateTargetData = {
    requestBody: DockerTargetCreate;
};

export type DockerCreateTargetResponse = (DockerTargetPublic);

export type DockerListTargetsData = {
    repoId?: (string | null);
};

export type DockerListTargetsResponse = (Array<DockerTargetPublic>);

export type DockerUpdateTargetData = {
    requestBody: ScanTargetUpdate;
    targetId: string;
};

export type DockerUpdateTargetResponse = (DockerTargetPublic);

export type DockerDeleteTargetData = {
    targetId: string;
};

export type DockerDeleteTargetResponse = (void);

export type DockerTriggerScanData = {
    branch?: (string | null);
    targetId: string;
};

export type DockerTriggerScanResponse = ({
    [key: string]: (string);
});

export type DockerListScansData = {
    limit?: number;
    targetId: string;
};

export type DockerListScansResponse = (Array<DockerScanPublic>);

export type DockerListFindingsData = {
    includeResolved?: boolean;
    targetId: string;
};

export type DockerListFindingsResponse = (Array<DockerFindingPublic>);

export type DockerGetFindingData = {
    dockerFindingId: string;
};

export type DockerGetFindingResponse = (DockerFindingPublic);

export type DockerIgnoreFindingData = {
    dockerFindingId: string;
};

export type DockerIgnoreFindingResponse = (DockerFindingPublic);

export type DockerUnignoreFindingData = {
    dockerFindingId: string;
};

export type DockerUnignoreFindingResponse = (DockerFindingPublic);

export type DockerListFilesData = {
    ref?: (string | null);
    targetId: string;
};

export type DockerListFilesResponse = (Array<DockerFilePublic>);

export type DockerListRuntimeFindingsData = {
    targetId: string;
};

export type DockerListRuntimeFindingsResponse = (Array<DockerBuildTelemetryPublic>);

export type DockerListRepositoryFixesData = {
    repoId: string;
};

export type DockerListRepositoryFixesResponse = (Array<DockerFixPublic>);

export type DockerListFixesData = {
    targetId: string;
};

export type DockerListFixesResponse = (Array<DockerFixPublic>);

export type DockerGenerateFixesData = {
    force?: boolean;
    requestBody?: (DockerFixGenerateRequest | null);
    targetId: string;
};

export type DockerGenerateFixesResponse = ({
    [key: string]: (string | number);
});

export type DockerGenerateRuntimeFixesData = {
    force?: boolean;
    requestBody: DockerRuntimeFixRequest;
    targetId: string;
};

export type DockerGenerateRuntimeFixesResponse = ({
    [key: string]: (string | number);
});

export type DockerDeliverFixesData = {
    force?: boolean;
    targetId: string;
};

export type DockerDeliverFixesResponse = ({
    [key: string]: (string);
});

export type DockerGetSarifData = {
    authorization?: (string | null);
};

export type DockerGetSarifResponse = ({
    [key: string]: unknown;
});

export type DockerTriggerScansForCodeScanningData = {
    authorization?: (string | null);
    branch?: (string | null);
};

export type DockerTriggerScansForCodeScanningResponse = ({
    [key: string]: (string);
});

export type EventsGetSseSignalsResponse = (Array<SSESignal>);

export type EventsGetSseEventSchemaResponse = (SSEEventPublic);

export type EventsCreateSseTicketResponse = ({
    [key: string]: (string | number);
});

export type EventsStreamEventsData = {
    ticket?: (string | null);
};

export type EventsStreamEventsResponse = (unknown);

export type InstallationsListInstallationsResponse = (Array<OrganizationPublic>);

export type InstallationsSyncInstallationsData = {
    requestBody: InstallationSyncRequest;
};

export type InstallationsSyncInstallationsResponse = (Array<OrganizationPublic>);

export type OrganizationsListAiProvidersResponse = (AIProvidersPublic);

export type OrganizationsListMyOrganizationsResponse = (Array<OrganizationPublic>);

export type OrganizationsUpdateOrganizationData = {
    orgId: string;
    requestBody: OrganizationUpdate;
};

export type OrganizationsUpdateOrganizationResponse = (OrganizationPublic);

export type OverviewGetOverviewData = {
    orgId?: (string | null);
    topRulesLimit?: number;
};

export type OverviewGetOverviewResponse = (OverviewPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RepositoriesListRepositoriesData = {
    enabled?: (boolean | null);
    limit?: number;
    orgId?: (string | null);
    skip?: number;
};

export type RepositoriesListRepositoriesResponse = (Array<RepositoryPublic>);

export type RepositoriesListExternalRepositoriesData = {
    limit?: number;
    skip?: number;
};

export type RepositoriesListExternalRepositoriesResponse = (Array<RepositoryPublic>);

export type RepositoriesCreateExternalRepositoryData = {
    requestBody: ExternalRepositoryCreate;
};

export type RepositoriesCreateExternalRepositoryResponse = (RepositoryPublic);

export type RepositoriesGetRepositoryData = {
    repoId: string;
};

export type RepositoriesGetRepositoryResponse = (RepositoryPublic);

export type RepositoriesUpdateRepositoryData = {
    repoId: string;
    requestBody: RepositoryUpdate;
};

export type RepositoriesUpdateRepositoryResponse = (RepositoryPublic);

export type RepositoriesSyncRepositoryWorkflowsData = {
    branch?: (string | null);
    repoId: string;
};

export type RepositoriesSyncRepositoryWorkflowsResponse = (WorkflowSyncSummary);

export type RepositoriesListRepositoryBranchesData = {
    repoId: string;
};

export type RepositoriesListRepositoryBranchesResponse = (Array<(string)>);

export type RepositoriesIntegrateActionData = {
    repoId: string;
};

export type RepositoriesIntegrateActionResponse = ({
    [key: string]: (string);
});

export type RulesListRulesData = {
    category?: (Category | null);
    enabled?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type RulesListRulesResponse = (Array<RulePublic>);

export type RulesGetRuleData = {
    ruleId: string;
};

export type RulesGetRuleResponse = (RulePublic);

export type RulesUpdateRuleData = {
    requestBody: RuleUpdate;
    ruleId: string;
};

export type RulesUpdateRuleResponse = (RulePublic);

export type SystemTestEmailData = {
    emailTo: string;
};

export type SystemTestEmailResponse = (Message);

export type SystemHealthResponse = (boolean);

export type SystemVersionResponse = (VersionInfo);

export type TelemetryIngestRunData = {
    authorization?: (string | null);
    requestBody: TelemetryPayload;
};

export type TelemetryIngestRunResponse = ({
    [key: string]: (string);
});

export type TelemetryIngestDockerBuildData = {
    authorization?: (string | null);
    requestBody: DockerBuildPayload;
};

export type TelemetryIngestDockerBuildResponse = ({
    [key: string]: (string);
});

export type TelemetryIngestSampleData = {
    authorization?: (string | null);
    requestBody: SamplePayload;
};

export type TelemetryIngestSampleResponse = ({
    [key: string]: (string);
});

export type TelemetryGetSummaryData = {
    limit?: number;
    repoId: string;
    skip?: number;
};

export type TelemetryGetSummaryResponse = (TelemetrySummaryPublic);

export type TelemetryListFindingsData = {
    repoId: string;
};

export type TelemetryListFindingsResponse = (Array<DynamicEnrichmentPublic>);

export type TelemetryTriggerScanData = {
    repoId: string;
};

export type TelemetryTriggerScanResponse = ({
    [key: string]: (string | number);
});

export type TerraformCreateRootData = {
    requestBody: TerraformRootCreate;
};

export type TerraformCreateRootResponse = (TerraformRootPublic);

export type TerraformListRootsData = {
    repoId?: (string | null);
};

export type TerraformListRootsResponse = (Array<TerraformRootPublic>);

export type TerraformUpdateRootData = {
    requestBody: ScanTargetUpdate;
    rootId: string;
};

export type TerraformUpdateRootResponse = (TerraformRootPublic);

export type TerraformDeleteRootData = {
    rootId: string;
};

export type TerraformDeleteRootResponse = (void);

export type TerraformTriggerScanData = {
    branch?: (string | null);
    rootId: string;
};

export type TerraformTriggerScanResponse = ({
    [key: string]: (string);
});

export type TerraformListScansData = {
    rootId: string;
};

export type TerraformListScansResponse = (Array<TerraformScanPublic>);

export type TerraformListFindingsData = {
    includeResolved?: boolean;
    rootId: string;
};

export type TerraformListFindingsResponse = (Array<TerraformFindingPublic>);

export type TerraformGetFindingData = {
    terraformFindingId: string;
};

export type TerraformGetFindingResponse = (TerraformFindingPublic);

export type TerraformIgnoreFindingData = {
    terraformFindingId: string;
};

export type TerraformIgnoreFindingResponse = (TerraformFindingPublic);

export type TerraformUnignoreFindingData = {
    terraformFindingId: string;
};

export type TerraformUnignoreFindingResponse = (TerraformFindingPublic);

export type TerraformListFilesData = {
    ref?: (string | null);
    rootId: string;
};

export type TerraformListFilesResponse = (Array<TerraformFilePublic>);

export type TerraformListRepositoryFixesData = {
    repoId: string;
};

export type TerraformListRepositoryFixesResponse = (Array<TerraformFixPublic>);

export type TerraformListFixesData = {
    rootId: string;
};

export type TerraformListFixesResponse = (Array<TerraformFixPublic>);

export type TerraformGenerateFixesData = {
    force?: boolean;
    requestBody?: (TerraformFixGenerateRequest | null);
    rootId: string;
};

export type TerraformGenerateFixesResponse = ({
    [key: string]: (string | number);
});

export type TerraformDeliverFixesData = {
    force?: boolean;
    rootId: string;
};

export type TerraformDeliverFixesResponse = ({
    [key: string]: (string);
});

export type TerraformGetSarifData = {
    authorization?: (string | null);
};

export type TerraformGetSarifResponse = ({
    [key: string]: unknown;
});

export type TerraformTriggerScansForCodeScanningData = {
    authorization?: (string | null);
    branch?: (string | null);
};

export type TerraformTriggerScansForCodeScanningResponse = ({
    [key: string]: (string);
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type WebhooksGithubWebhookData = {
    xGithubDelivery?: (string | null);
    xGithubEvent?: (string | null);
    xHubSignature256?: (string | null);
};

export type WebhooksGithubWebhookResponse = ({
    [key: string]: (string);
});

export type WebhooksStripeWebhookData = {
    stripeSignature?: (string | null);
};

export type WebhooksStripeWebhookResponse = ({
    [key: string]: (string);
});

export type WorkflowListScansData = {
    branch?: (string | null);
    grade?: (string | null);
    limit?: number;
    repoId?: (string | null);
    skip?: number;
    status?: (ScanStatus | null);
};

export type WorkflowListScansResponse = (Array<WorkflowScanPublic>);

export type WorkflowTriggerScansForCodeScanningData = {
    authorization?: (string | null);
    branch?: (string | null);
};

export type WorkflowTriggerScansForCodeScanningResponse = ({
    [key: string]: (string);
});

export type WorkflowGetScanData = {
    scanId: string;
};

export type WorkflowGetScanResponse = (WorkflowScanPublic);

export type WorkflowTriggerRepositoryScanData = {
    branch?: (string | null);
    force?: boolean;
    repoId: string;
};

export type WorkflowTriggerRepositoryScanResponse = ({
    [key: string]: (string);
});

export type WorkflowTriggerFileScanData = {
    force?: boolean;
    workflowFileId: string;
};

export type WorkflowTriggerFileScanResponse = ({
    [key: string]: (string);
});

export type WorkflowBackfillScansResponse = ({
    [key: string]: (string);
});

export type WorkflowListFilesData = {
    branch?: (string | null);
    repoId: string;
};

export type WorkflowListFilesResponse = (Array<WorkflowFilePublic>);

export type WorkflowGetSarifData = {
    authorization?: (string | null);
};

export type WorkflowGetSarifResponse = ({
    [key: string]: unknown;
});

export type WorkflowListFindingsData = {
    branch?: (string | null);
    category?: (Category | null);
    includeIgnored?: boolean;
    includeResolved?: boolean;
    latestOnly?: boolean;
    limit?: number;
    repoId?: (string | null);
    scanId?: (string | null);
    severity?: (Severity | null);
    skip?: number;
    unfixed?: boolean;
};

export type WorkflowListFindingsResponse = (Array<WorkflowFindingPublic>);

export type WorkflowGetFindingStatsData = {
    branch?: (string | null);
    latestOnly?: boolean;
    repoId?: (string | null);
};

export type WorkflowGetFindingStatsResponse = (WorkflowFindingStatsPublic);

export type WorkflowGetFindingData = {
    findingId: string;
};

export type WorkflowGetFindingResponse = (WorkflowFindingPublic);

export type WorkflowIgnoreFindingData = {
    findingId: string;
};

export type WorkflowIgnoreFindingResponse = (WorkflowFindingPublic);

export type WorkflowUnignoreFindingData = {
    findingId: string;
};

export type WorkflowUnignoreFindingResponse = (WorkflowFindingPublic);

export type WorkflowListFixesData = {
    branch?: (string | null);
    limit?: number;
    repoId?: (string | null);
    skip?: number;
    status?: (FixStatus | null);
};

export type WorkflowListFixesResponse = (Array<WorkflowFixPublic>);

export type WorkflowListPullRequestsData = {
    repoId: string;
};

export type WorkflowListPullRequestsResponse = (Array<PullRequestPublic>);

export type WorkflowGetFixData = {
    fixId: string;
};

export type WorkflowGetFixResponse = (WorkflowFixPublic);

export type WorkflowRejectFixData = {
    fixId: string;
};

export type WorkflowRejectFixResponse = (void);

export type WorkflowGenerateRepositoryFixesData = {
    force?: boolean;
    repoId: string;
    requestBody?: BatchFixRequest;
};

export type WorkflowGenerateRepositoryFixesResponse = ({
    [key: string]: (number);
});

export type WorkflowDeliverFixData = {
    fixId: string;
    force?: boolean;
};

export type WorkflowDeliverFixResponse = ({
    [key: string]: (string);
});

export type WorkflowDeliverRepositoryFixesData = {
    force?: boolean;
    repoId: string;
};

export type WorkflowDeliverRepositoryFixesResponse = ({
    [key: string]: (string);
});

export type WorkflowRegenerateRepositoryFixesData = {
    repoId: string;
};

export type WorkflowRegenerateRepositoryFixesResponse = ({
    [key: string]: (number);
});

export type WorkflowRegenerateFixData = {
    fixId: string;
};

export type WorkflowRegenerateFixResponse = ({
    [key: string]: (number);
});

export type WorkflowRetryFixData = {
    fixId: string;
};

export type WorkflowRetryFixResponse = ({
    [key: string]: (string);
});

export type WorkflowSyncPullRequestStatusesData = {
    repoId: string;
};

export type WorkflowSyncPullRequestStatusesResponse = ({
    [key: string]: (number);
});
