import asyncio
import logging
import uuid
from datetime import datetime, timezone

from sqlmodel import Session

from app.core.db import engine
from app.models import Fix, FixDeliveryMode, FixStatus, Repository, WorkflowFile
from app.workers.celery_app import celery_app

logger = logging.getLogger(__name__)


@celery_app.task(name="fix_delivery.deliver", bind=True, max_retries=3)
def deliver_fix(
    self: object,  # noqa: ARG001
    fix_id: str,
) -> dict[str, str]:
    with Session(engine) as session:
        fix = session.get(Fix, uuid.UUID(fix_id))
        if not fix:
            return {"status": "error", "detail": "fix_not_found"}
        if fix.status != FixStatus.ready:
            return {"status": "error", "detail": f"fix_not_ready: {fix.status}"}

        issue = fix.issue
        if not issue:
            return {"status": "error", "detail": "issue_not_found"}

        analysis = issue.analysis
        repo = session.get(Repository, analysis.repo_id) if analysis else None
        if not repo:
            return {"status": "error", "detail": "repository_not_found"}

        wf_file = (
            session.get(WorkflowFile, analysis.workflow_file_id) if analysis else None
        )
        if not wf_file:
            return {"status": "error", "detail": "workflow_file_not_found"}

        # Determine delivery mode (repo → org → pr)
        delivery_mode = (
            repo.fix_delivery_mode
            or (repo.organization.fix_delivery_mode if repo.organization else None)
            or FixDeliveryMode.pr
        )

        if delivery_mode == FixDeliveryMode.disabled:
            logger.info("Fix delivery disabled for repo %s", repo.full_name)
            return {"status": "skipped", "reason": "delivery_disabled"}

        fix.status = FixStatus.delivering
        session.add(fix)
        session.commit()

        result = asyncio.run(
            _deliver(
                installation_id=repo.installation_id,
                full_name=repo.full_name,
                base_branch=analysis.branch or repo.default_branch,
                file_path=wf_file.path,
                new_content=fix.diff or wf_file.raw_content,
                fix_id=fix_id,
                rule_slug=issue.rule.slug if issue.rule else "fix",
                delivery_mode=delivery_mode.value,
            )
        )

        if result.error:
            fix.status = FixStatus.failed
            fix.error_message = result.error
        else:
            fix.status = FixStatus.delivered
            fix.pr_url = result.pr_url
            fix.comment_url = result.comment_url
            fix.delivered_at = datetime.now(timezone.utc)

        session.add(fix)
        session.commit()
        return {"status": fix.status.value, "fix_id": fix_id}


async def _deliver(
    installation_id: int,
    full_name: str,
    base_branch: str,
    file_path: str,
    new_content: str,
    fix_id: str,
    rule_slug: str,
    delivery_mode: str,
) -> object:
    import redis.asyncio as aioredis

    from app.core.config import settings
    from app.services.github.app_client import GitHubAppClient
    from app.services.github.fix_delivery import FixDeliveryService

    r = aioredis.from_url(settings.REDIS_URL)
    try:
        client = GitHubAppClient(redis_client=r)
        svc = FixDeliveryService(app_client=client)

        if delivery_mode == "pr":
            fix_branch = f"greensecops/fix-{rule_slug}-{fix_id[:8]}"
            return await svc.deliver_as_pr(
                installation_id=installation_id,
                full_name=full_name,
                base_branch=base_branch,
                fix_branch=fix_branch,
                file_path=file_path,
                new_content=new_content,
                pr_title=f"fix(ci): {rule_slug.replace('_', ' ')}",
                pr_body=f"Automated fix generated by GreenSecOps for rule `{rule_slug}`.\n\nFix ID: `{fix_id}`",
            )
        else:
            return await svc.deliver_as_comment(
                installation_id=installation_id,
                full_name=full_name,
                issue_number=1,
                body=f"**GreenSecOps Fix** for `{rule_slug}`:\n\n```yaml\n{new_content}\n```",
            )
    finally:
        await r.aclose()
