from dataclasses import dataclass

from app.models.enums import IssueSeverity

_SEVERITY_EMOJI: dict[str, str] = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
    "info": "⚪",
}

_SEVERITY_ORDER: dict[str, int] = {s.value: i for i, s in enumerate(IssueSeverity)}


@dataclass
class IssueInfo:
    rule_slug: str
    rule_title: str
    category: str
    severity: str
    message: str
    line_start: int | None = None


def build_pr_body(
    issues: list[IssueInfo],
    fix_ids: list[str],
    wiki_base_url: str,
    frontend_host: str,
    bot_handle: str,
    app_name: str = "GreenSecOps",
    app_url: str = "https://greensecops.io",
) -> str:
    sorted_issues = sorted(
        issues, key=lambda i: (_SEVERITY_ORDER.get(i.severity, 99), i.rule_title)
    )
    rows = "\n".join(
        f"| [{i.rule_title}]({wiki_base_url}/{i.rule_slug}) "
        f"| {i.category.title()} "
        f"| {_SEVERITY_EMOJI.get(i.severity, '')} {i.severity.title()} "
        f"| {i.message} |"
        for i in sorted_issues
    )
    fix_ids_str = ", ".join(f"`{fid}`" for fid in fix_ids[:5])
    if len(fix_ids) > 5:
        fix_ids_str += f" and {len(fix_ids) - 5} more"

    return f"""\
## 🌿 {app_name} — Automated Fix

This PR was automatically generated by **[{app_name}]({app_url})**, a tool that continuously analyses your GitHub Actions workflows for security, performance, energy efficiency, reliability, and maintainability issues.

---

## Issues Fixed

| Rule | Category | Severity | Message |
|------|----------|----------|---------|
{rows}

---

## How to Interact

Comment on this PR to control {app_name}:

| Command | Effect |
|---------|--------|
| `{bot_handle} disable` | Disable auto-fix PRs for **this repository** |
| `{bot_handle} disable-all` | Disable auto-fix PRs for **all your repositories** |

---

🔗 [View on {app_name}]({frontend_host}) · [Register for free]({frontend_host}/signup)

<sub>Fix IDs: {fix_ids_str}</sub>"""
