default_stages: [pre-commit]

repos:
  # Landing: biome lint + format
  - repo: local
    hooks:
      - id: biome-check-landing
        name: Biome lint & format (landing)
        entry: bunx biome check --config-path=. --write --unsafe --no-errors-on-unmatched --files-ignore-unknown=true ./
        language: system
        files: \.(ts|tsx|js|jsx|json)$
        pass_filenames: false
