/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRulesRouteImport } from './routes/_layout/rules'
import { Route as LayoutRepositoriesRouteImport } from './routes/_layout/repositories'
import { Route as LayoutInfrastructureRouteImport } from './routes/_layout/infrastructure'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutBillingRouteImport } from './routes/_layout/billing'
import { Route as LayoutBadgesRouteImport } from './routes/_layout/badges'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutRepositoriesIndexRouteImport } from './routes/_layout/repositories/index'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth/github/callback'
import { Route as AuthGithubAppCallbackRouteImport } from './routes/auth/github/app-callback'
import { Route as LayoutRepositoriesRepoIdRouteImport } from './routes/_layout/repositories/$repoId'
import { Route as LayoutFixesFixIdRouteImport } from './routes/_layout/fixes/$fixId'
import { Route as LayoutAnalysesAnalysisIdRouteImport } from './routes/_layout/analyses/$analysisId'
import { Route as LayoutRepositoriesRepoIdIndexRouteImport } from './routes/_layout/repositories/$repoId/index'
import { Route as LayoutRepositoriesRepoIdTelemetryRouteImport } from './routes/_layout/repositories/$repoId/telemetry'
import { Route as LayoutRepositoriesRepoIdStaticAnalysisRouteImport } from './routes/_layout/repositories/$repoId/static-analysis'
import { Route as LayoutRepositoriesRepoIdPullRequestsRouteImport } from './routes/_layout/repositories/$repoId/pull-requests'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRulesRoute = LayoutRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRepositoriesRoute = LayoutRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInfrastructureRoute = LayoutInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBillingRoute = LayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBadgesRoute = LayoutBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRepositoriesIndexRoute = LayoutRepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRepositoriesRoute,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubAppCallbackRoute = AuthGithubAppCallbackRouteImport.update({
  id: '/auth/github/app-callback',
  path: '/auth/github/app-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRepositoriesRepoIdRoute =
  LayoutRepositoriesRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => LayoutRepositoriesRoute,
  } as any)
const LayoutFixesFixIdRoute = LayoutFixesFixIdRouteImport.update({
  id: '/fixes/$fixId',
  path: '/fixes/$fixId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalysesAnalysisIdRoute =
  LayoutAnalysesAnalysisIdRouteImport.update({
    id: '/analyses/$analysisId',
    path: '/analyses/$analysisId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutRepositoriesRepoIdIndexRoute =
  LayoutRepositoriesRepoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutRepositoriesRepoIdRoute,
  } as any)
const LayoutRepositoriesRepoIdTelemetryRoute =
  LayoutRepositoriesRepoIdTelemetryRouteImport.update({
    id: '/telemetry',
    path: '/telemetry',
    getParentRoute: () => LayoutRepositoriesRepoIdRoute,
  } as any)
const LayoutRepositoriesRepoIdStaticAnalysisRoute =
  LayoutRepositoriesRepoIdStaticAnalysisRouteImport.update({
    id: '/static-analysis',
    path: '/static-analysis',
    getParentRoute: () => LayoutRepositoriesRepoIdRoute,
  } as any)
const LayoutRepositoriesRepoIdPullRequestsRoute =
  LayoutRepositoriesRepoIdPullRequestsRouteImport.update({
    id: '/pull-requests',
    path: '/pull-requests',
    getParentRoute: () => LayoutRepositoriesRepoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/badges': typeof LayoutBadgesRoute
  '/billing': typeof LayoutBillingRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/infrastructure': typeof LayoutInfrastructureRoute
  '/repositories': typeof LayoutRepositoriesRouteWithChildren
  '/rules': typeof LayoutRulesRoute
  '/settings': typeof LayoutSettingsRoute
  '/analyses/$analysisId': typeof LayoutAnalysesAnalysisIdRoute
  '/fixes/$fixId': typeof LayoutFixesFixIdRoute
  '/repositories/$repoId': typeof LayoutRepositoriesRepoIdRouteWithChildren
  '/auth/github/app-callback': typeof AuthGithubAppCallbackRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/repositories/': typeof LayoutRepositoriesIndexRoute
  '/repositories/$repoId/pull-requests': typeof LayoutRepositoriesRepoIdPullRequestsRoute
  '/repositories/$repoId/static-analysis': typeof LayoutRepositoriesRepoIdStaticAnalysisRoute
  '/repositories/$repoId/telemetry': typeof LayoutRepositoriesRepoIdTelemetryRoute
  '/repositories/$repoId/': typeof LayoutRepositoriesRepoIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/badges': typeof LayoutBadgesRoute
  '/billing': typeof LayoutBillingRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/infrastructure': typeof LayoutInfrastructureRoute
  '/rules': typeof LayoutRulesRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/analyses/$analysisId': typeof LayoutAnalysesAnalysisIdRoute
  '/fixes/$fixId': typeof LayoutFixesFixIdRoute
  '/auth/github/app-callback': typeof AuthGithubAppCallbackRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/repositories': typeof LayoutRepositoriesIndexRoute
  '/repositories/$repoId/pull-requests': typeof LayoutRepositoriesRepoIdPullRequestsRoute
  '/repositories/$repoId/static-analysis': typeof LayoutRepositoriesRepoIdStaticAnalysisRoute
  '/repositories/$repoId/telemetry': typeof LayoutRepositoriesRepoIdTelemetryRoute
  '/repositories/$repoId': typeof LayoutRepositoriesRepoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/badges': typeof LayoutBadgesRoute
  '/_layout/billing': typeof LayoutBillingRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/infrastructure': typeof LayoutInfrastructureRoute
  '/_layout/repositories': typeof LayoutRepositoriesRouteWithChildren
  '/_layout/rules': typeof LayoutRulesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/analyses/$analysisId': typeof LayoutAnalysesAnalysisIdRoute
  '/_layout/fixes/$fixId': typeof LayoutFixesFixIdRoute
  '/_layout/repositories/$repoId': typeof LayoutRepositoriesRepoIdRouteWithChildren
  '/auth/github/app-callback': typeof AuthGithubAppCallbackRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/_layout/repositories/': typeof LayoutRepositoriesIndexRoute
  '/_layout/repositories/$repoId/pull-requests': typeof LayoutRepositoriesRepoIdPullRequestsRoute
  '/_layout/repositories/$repoId/static-analysis': typeof LayoutRepositoriesRepoIdStaticAnalysisRoute
  '/_layout/repositories/$repoId/telemetry': typeof LayoutRepositoriesRepoIdTelemetryRoute
  '/_layout/repositories/$repoId/': typeof LayoutRepositoriesRepoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/badges'
    | '/billing'
    | '/dashboard'
    | '/infrastructure'
    | '/repositories'
    | '/rules'
    | '/settings'
    | '/analyses/$analysisId'
    | '/fixes/$fixId'
    | '/repositories/$repoId'
    | '/auth/github/app-callback'
    | '/auth/github/callback'
    | '/repositories/'
    | '/repositories/$repoId/pull-requests'
    | '/repositories/$repoId/static-analysis'
    | '/repositories/$repoId/telemetry'
    | '/repositories/$repoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/badges'
    | '/billing'
    | '/dashboard'
    | '/infrastructure'
    | '/rules'
    | '/settings'
    | '/'
    | '/analyses/$analysisId'
    | '/fixes/$fixId'
    | '/auth/github/app-callback'
    | '/auth/github/callback'
    | '/repositories'
    | '/repositories/$repoId/pull-requests'
    | '/repositories/$repoId/static-analysis'
    | '/repositories/$repoId/telemetry'
    | '/repositories/$repoId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/badges'
    | '/_layout/billing'
    | '/_layout/dashboard'
    | '/_layout/infrastructure'
    | '/_layout/repositories'
    | '/_layout/rules'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/analyses/$analysisId'
    | '/_layout/fixes/$fixId'
    | '/_layout/repositories/$repoId'
    | '/auth/github/app-callback'
    | '/auth/github/callback'
    | '/_layout/repositories/'
    | '/_layout/repositories/$repoId/pull-requests'
    | '/_layout/repositories/$repoId/static-analysis'
    | '/_layout/repositories/$repoId/telemetry'
    | '/_layout/repositories/$repoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthGithubAppCallbackRoute: typeof AuthGithubAppCallbackRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rules': {
      id: '/_layout/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof LayoutRulesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/repositories': {
      id: '/_layout/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof LayoutRepositoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/infrastructure': {
      id: '/_layout/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof LayoutInfrastructureRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/billing': {
      id: '/_layout/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof LayoutBillingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/badges': {
      id: '/_layout/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof LayoutBadgesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/repositories/': {
      id: '/_layout/repositories/'
      path: '/'
      fullPath: '/repositories/'
      preLoaderRoute: typeof LayoutRepositoriesIndexRouteImport
      parentRoute: typeof LayoutRepositoriesRoute
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/app-callback': {
      id: '/auth/github/app-callback'
      path: '/auth/github/app-callback'
      fullPath: '/auth/github/app-callback'
      preLoaderRoute: typeof AuthGithubAppCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/repositories/$repoId': {
      id: '/_layout/repositories/$repoId'
      path: '/$repoId'
      fullPath: '/repositories/$repoId'
      preLoaderRoute: typeof LayoutRepositoriesRepoIdRouteImport
      parentRoute: typeof LayoutRepositoriesRoute
    }
    '/_layout/fixes/$fixId': {
      id: '/_layout/fixes/$fixId'
      path: '/fixes/$fixId'
      fullPath: '/fixes/$fixId'
      preLoaderRoute: typeof LayoutFixesFixIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analyses/$analysisId': {
      id: '/_layout/analyses/$analysisId'
      path: '/analyses/$analysisId'
      fullPath: '/analyses/$analysisId'
      preLoaderRoute: typeof LayoutAnalysesAnalysisIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/repositories/$repoId/': {
      id: '/_layout/repositories/$repoId/'
      path: '/'
      fullPath: '/repositories/$repoId/'
      preLoaderRoute: typeof LayoutRepositoriesRepoIdIndexRouteImport
      parentRoute: typeof LayoutRepositoriesRepoIdRoute
    }
    '/_layout/repositories/$repoId/telemetry': {
      id: '/_layout/repositories/$repoId/telemetry'
      path: '/telemetry'
      fullPath: '/repositories/$repoId/telemetry'
      preLoaderRoute: typeof LayoutRepositoriesRepoIdTelemetryRouteImport
      parentRoute: typeof LayoutRepositoriesRepoIdRoute
    }
    '/_layout/repositories/$repoId/static-analysis': {
      id: '/_layout/repositories/$repoId/static-analysis'
      path: '/static-analysis'
      fullPath: '/repositories/$repoId/static-analysis'
      preLoaderRoute: typeof LayoutRepositoriesRepoIdStaticAnalysisRouteImport
      parentRoute: typeof LayoutRepositoriesRepoIdRoute
    }
    '/_layout/repositories/$repoId/pull-requests': {
      id: '/_layout/repositories/$repoId/pull-requests'
      path: '/pull-requests'
      fullPath: '/repositories/$repoId/pull-requests'
      preLoaderRoute: typeof LayoutRepositoriesRepoIdPullRequestsRouteImport
      parentRoute: typeof LayoutRepositoriesRepoIdRoute
    }
  }
}

interface LayoutRepositoriesRepoIdRouteChildren {
  LayoutRepositoriesRepoIdPullRequestsRoute: typeof LayoutRepositoriesRepoIdPullRequestsRoute
  LayoutRepositoriesRepoIdStaticAnalysisRoute: typeof LayoutRepositoriesRepoIdStaticAnalysisRoute
  LayoutRepositoriesRepoIdTelemetryRoute: typeof LayoutRepositoriesRepoIdTelemetryRoute
  LayoutRepositoriesRepoIdIndexRoute: typeof LayoutRepositoriesRepoIdIndexRoute
}

const LayoutRepositoriesRepoIdRouteChildren: LayoutRepositoriesRepoIdRouteChildren =
  {
    LayoutRepositoriesRepoIdPullRequestsRoute:
      LayoutRepositoriesRepoIdPullRequestsRoute,
    LayoutRepositoriesRepoIdStaticAnalysisRoute:
      LayoutRepositoriesRepoIdStaticAnalysisRoute,
    LayoutRepositoriesRepoIdTelemetryRoute:
      LayoutRepositoriesRepoIdTelemetryRoute,
    LayoutRepositoriesRepoIdIndexRoute: LayoutRepositoriesRepoIdIndexRoute,
  }

const LayoutRepositoriesRepoIdRouteWithChildren =
  LayoutRepositoriesRepoIdRoute._addFileChildren(
    LayoutRepositoriesRepoIdRouteChildren,
  )

interface LayoutRepositoriesRouteChildren {
  LayoutRepositoriesRepoIdRoute: typeof LayoutRepositoriesRepoIdRouteWithChildren
  LayoutRepositoriesIndexRoute: typeof LayoutRepositoriesIndexRoute
}

const LayoutRepositoriesRouteChildren: LayoutRepositoriesRouteChildren = {
  LayoutRepositoriesRepoIdRoute: LayoutRepositoriesRepoIdRouteWithChildren,
  LayoutRepositoriesIndexRoute: LayoutRepositoriesIndexRoute,
}

const LayoutRepositoriesRouteWithChildren =
  LayoutRepositoriesRoute._addFileChildren(LayoutRepositoriesRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBadgesRoute: typeof LayoutBadgesRoute
  LayoutBillingRoute: typeof LayoutBillingRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutInfrastructureRoute: typeof LayoutInfrastructureRoute
  LayoutRepositoriesRoute: typeof LayoutRepositoriesRouteWithChildren
  LayoutRulesRoute: typeof LayoutRulesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAnalysesAnalysisIdRoute: typeof LayoutAnalysesAnalysisIdRoute
  LayoutFixesFixIdRoute: typeof LayoutFixesFixIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBadgesRoute: LayoutBadgesRoute,
  LayoutBillingRoute: LayoutBillingRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutInfrastructureRoute: LayoutInfrastructureRoute,
  LayoutRepositoriesRoute: LayoutRepositoriesRouteWithChildren,
  LayoutRulesRoute: LayoutRulesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAnalysesAnalysisIdRoute: LayoutAnalysesAnalysisIdRoute,
  LayoutFixesFixIdRoute: LayoutFixesFixIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthGithubAppCallbackRoute: AuthGithubAppCallbackRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
