/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutBadgesRouteImport } from './routes/_layout/badges'
import { Route as LayoutBillingRouteImport } from './routes/_layout/billing'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutDockerRouteImport } from './routes/_layout/docker'
import { Route as LayoutInfrastructureRouteImport } from './routes/_layout/infrastructure'
import { Route as LayoutRepositoriesRouteImport } from './routes/_layout/repositories'
import { Route as LayoutRulesRouteImport } from './routes/_layout/rules'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAnalysesAnalysisIdRouteImport } from './routes/_layout/analyses/$analysisId'
import { Route as LayoutBadgesIndexRouteImport } from './routes/_layout/badges/index'
import { Route as LayoutBadgesAnsibleRouteImport } from './routes/_layout/badges/ansible'
import { Route as LayoutBadgesDockerRouteImport } from './routes/_layout/badges/docker'
import { Route as LayoutBadgesRepositoriesRouteImport } from './routes/_layout/badges/repositories'
import { Route as LayoutBadgesTerraformRouteImport } from './routes/_layout/badges/terraform'
import { Route as LayoutDockerIndexRouteImport } from './routes/_layout/docker/index'
import { Route as LayoutDockerRepoIdRouteImport } from './routes/_layout/docker/$repoId'
import { Route as LayoutDockerBadgesRouteImport } from './routes/_layout/docker/badges'
import { Route as LayoutFixesFixIdRouteImport } from './routes/_layout/fixes/$fixId'
import { Route as LayoutInfrastructureIndexRouteImport } from './routes/_layout/infrastructure/index'
import { Route as LayoutInfrastructureRepoIdRouteImport } from './routes/_layout/infrastructure/$repoId'
import { Route as LayoutInfrastructureAnsibleRouteImport } from './routes/_layout/infrastructure/ansible'
import { Route as LayoutInfrastructureBadgesRouteImport } from './routes/_layout/infrastructure/badges'
import { Route as LayoutRepositoriesIndexRouteImport } from './routes/_layout/repositories/index'
import { Route as LayoutRepositoriesRepoIdRouteImport } from './routes/_layout/repositories/$repoId'
import { Route as AuthGithubAppCallbackRouteImport } from './routes/auth/github/app-callback'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth/github/callback'
import { Route as LayoutDockerRepoIdIndexRouteImport } from './routes/_layout/docker/$repoId/index'
import { Route as LayoutDockerRepoIdAnalysisRouteImport } from './routes/_layout/docker/$repoId/analysis'
import { Route as LayoutDockerRepoIdPullRequestsRouteImport } from './routes/_layout/docker/$repoId/pull-requests'
import { Route as LayoutDockerRepoIdRuntimeRouteImport } from './routes/_layout/docker/$repoId/runtime'
import { Route as LayoutDockerRepoIdScansRouteImport } from './routes/_layout/docker/$repoId/scans'
import { Route as LayoutInfrastructureRepoIdIndexRouteImport } from './routes/_layout/infrastructure/$repoId/index'
import { Route as LayoutInfrastructureRepoIdAnsibleRouteImport } from './routes/_layout/infrastructure/$repoId/ansible'
import { Route as LayoutInfrastructureRepoIdCloudRouteImport } from './routes/_layout/infrastructure/$repoId/cloud'
import { Route as LayoutInfrastructureRepoIdDockerRouteImport } from './routes/_layout/infrastructure/$repoId/docker'
import { Route as LayoutInfrastructureRepoIdPullRequestsRouteImport } from './routes/_layout/infrastructure/$repoId/pull-requests'
import { Route as LayoutInfrastructureRepoIdTerraformRouteImport } from './routes/_layout/infrastructure/$repoId/terraform'
import { Route as LayoutRepositoriesRepoIdIndexRouteImport } from './routes/_layout/repositories/$repoId/index'
import { Route as LayoutRepositoriesRepoIdPullRequestsRouteImport } from './routes/_layout/repositories/$repoId/pull-requests'
import { Route as LayoutRepositoriesRepoIdStaticAnalysisRouteImport } from './routes/_layout/repositories/$repoId/static-analysis'
import { Route as LayoutRepositoriesRepoIdTelemetryRouteImport } from './routes/_layout/repositories/$repoId/telemetry'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBadgesRoute = LayoutBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBillingRoute = LayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDockerRoute = LayoutDockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInfrastructureRoute = LayoutInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRepositoriesRoute = LayoutRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRulesRoute = LayoutRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalysesAnalysisIdRoute =
  LayoutAnalysesAnalysisIdRouteImport.update({
    id: '/analyses/$analysisId',
    path: '/analyses/$analysisId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutBadgesIndexRoute = LayoutBadgesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutBadgesRoute,
} as any)
const LayoutBadgesAnsibleRoute = LayoutBadgesAnsibleRouteImport.update({
  id: '/ansible',
  path: '/ansible',
  getParentRoute: () => LayoutBadgesRoute,
} as any)
const LayoutBadgesDockerRoute = LayoutBadgesDockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => LayoutBadgesRoute,
} as any)
const LayoutBadgesRepositoriesRoute =
  LayoutBadgesRepositoriesRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => LayoutBadgesRoute,
  } as any)
const LayoutBadgesTerraformRoute = LayoutBadgesTerraformRouteImport.update({
  id: '/terraform',
  path: '/terraform',
  getParentRoute: () => LayoutBadgesRoute,
} as any)
const LayoutDockerIndexRoute = LayoutDockerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutDockerRoute,
} as any)
const LayoutDockerRepoIdRoute = LayoutDockerRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => LayoutDockerRoute,
} as any)
const LayoutDockerBadgesRoute = LayoutDockerBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => LayoutDockerRoute,
} as any)
const LayoutFixesFixIdRoute = LayoutFixesFixIdRouteImport.update({
  id: '/fixes/$fixId',
  path: '/fixes/$fixId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInfrastructureIndexRoute =
  LayoutInfrastructureIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutInfrastructureRoute,
  } as any)
const LayoutInfrastructureRepoIdRoute =
  LayoutInfrastructureRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => LayoutInfrastructureRoute,
  } as any)
const LayoutInfrastructureAnsibleRoute =
  LayoutInfrastructureAnsibleRouteImport.update({
    id: '/ansible',
    path: '/ansible',
    getParentRoute: () => LayoutInfrastructureRoute,
  } as any)
const LayoutInfrastructureBadgesRoute =
  LayoutInfrastructureBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => LayoutInfrastructureRoute,
  } as any)
const LayoutRepositoriesIndexRoute = LayoutRepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRepositoriesRoute,
} as any)
const LayoutRepositoriesRepoIdRoute =
  LayoutRepositoriesRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => LayoutRepositoriesRoute,
  } as any)
const AuthGithubAppCallbackRoute = AuthGithubAppCallbackRouteImport.update({
  id: '/auth/github/app-callback',
  path: '/auth/github/app-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDockerRepoIdIndexRoute = LayoutDockerRepoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutDockerRepoIdRoute,
} as any)
const LayoutDockerRepoIdAnalysisRoute =
  LayoutDockerRepoIdAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => LayoutDockerRepoIdRoute,
  } as any)
const LayoutDockerRepoIdPullRequestsRoute =
  LayoutDockerRepoIdPullRequestsRouteImport.update({
    id: '/pull-requests',
    path: '/pull-requests',
    getParentRoute: () => LayoutDockerRepoIdRoute,
  } as any)
const LayoutDockerRepoIdRuntimeRoute =
  LayoutDockerRepoIdRuntimeRouteImport.update({
    id: '/runtime',
    path: '/runtime',
    getParentRoute: () => LayoutDockerRepoIdRoute,
  } as any)
const LayoutDockerRepoIdScansRoute = LayoutDockerRepoIdScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => LayoutDockerRepoIdRoute,
} as any)
const LayoutInfrastructureRepoIdIndexRoute =
  LayoutInfrastructureRepoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutInfrastructureRepoIdRoute,
  } as any)
const LayoutInfrastructureRepoIdAnsibleRoute =
  LayoutInfrastructureRepoIdAnsibleRouteImport.update({
    id: '/ansible',
    path: '/ansible',
    getParentRoute: () => LayoutInfrastructureRepoIdRoute,
  } as any)
const LayoutInfrastructureRepoIdCloudRoute =
  LayoutInfrastructureRepoIdCloudRouteImport.update({
    id: '/cloud',
    path: '/cloud',
    getParentRoute: () => LayoutInfrastructureRepoIdRoute,
  } as any)
const LayoutInfrastructureRepoIdDockerRoute =
  LayoutInfrastructureRepoIdDockerRouteImport.update({
    id: '/docker',
    path: '/docker',
    getParentRoute: () => LayoutInfrastructureRepoIdRoute,
  } as any)
const LayoutInfrastructureRepoIdPullRequestsRoute =
  LayoutInfrastructureRepoIdPullRequestsRouteImport.update({
    id: '/pull-requests',
    path: '/pull-requests',
    getParentRoute: () => LayoutInfrastructureRepoIdRoute,
  } as any)
const LayoutInfrastructureRepoIdTerraformRoute =
  LayoutInfrastructureRepoIdTerraformRouteImport.update({
    id: '/terraform',
    path: '/terraform',
    getParentRoute: () => LayoutInfrastructureRepoIdRoute,
  } as any)
const LayoutRepositoriesRepoIdIndexRoute =
  LayoutRepositoriesRepoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutRepositoriesRepoIdRoute,
  } as any)
const LayoutRepositoriesRepoIdPullRequestsRoute =
  LayoutRepositoriesRepoIdPullRequestsRouteImport.update({
    id: '/pull-requests',
    path: '/pull-requests',
    getParentRoute: () => LayoutRepositoriesRepoIdRoute,
  } as any)
const LayoutRepositoriesRepoIdStaticAnalysisRoute =
  LayoutRepositoriesRepoIdStaticAnalysisRouteImport.update({
    id: '/static-analysis',
    path: '/static-analysis',
    getParentRoute: () => LayoutRepositoriesRepoIdRoute,
  } as any)
const LayoutRepositoriesRepoIdTelemetryRoute =
  LayoutRepositoriesRepoIdTelemetryRouteImport.update({
    id: '/telemetry',
    path: '/telemetry',
    getParentRoute: () => LayoutRepositoriesRepoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/badges': typeof LayoutBadgesRouteWithChildren
  '/billing': typeof LayoutBillingRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/docker': typeof LayoutDockerRouteWithChildren
  '/infrastructure': typeof LayoutInfrastructureRouteWithChildren
  '/repositories': typeof LayoutRepositoriesRouteWithChildren
  '/rules': typeof LayoutRulesRoute
  '/settings': typeof LayoutSettingsRoute
  '/analyses/$analysisId': typeof LayoutAnalysesAnalysisIdRoute
  '/badges/ansible': typeof LayoutBadgesAnsibleRoute
  '/badges/docker': typeof LayoutBadgesDockerRoute
  '/badges/repositories': typeof LayoutBadgesRepositoriesRoute
  '/badges/terraform': typeof LayoutBadgesTerraformRoute
  '/docker/$repoId': typeof LayoutDockerRepoIdRouteWithChildren
  '/docker/badges': typeof LayoutDockerBadgesRoute
  '/fixes/$fixId': typeof LayoutFixesFixIdRoute
  '/infrastructure/$repoId': typeof LayoutInfrastructureRepoIdRouteWithChildren
  '/infrastructure/ansible': typeof LayoutInfrastructureAnsibleRoute
  '/infrastructure/badges': typeof LayoutInfrastructureBadgesRoute
  '/repositories/$repoId': typeof LayoutRepositoriesRepoIdRouteWithChildren
  '/auth/github/app-callback': typeof AuthGithubAppCallbackRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/badges/': typeof LayoutBadgesIndexRoute
  '/docker/': typeof LayoutDockerIndexRoute
  '/infrastructure/': typeof LayoutInfrastructureIndexRoute
  '/repositories/': typeof LayoutRepositoriesIndexRoute
  '/docker/$repoId/analysis': typeof LayoutDockerRepoIdAnalysisRoute
  '/docker/$repoId/pull-requests': typeof LayoutDockerRepoIdPullRequestsRoute
  '/docker/$repoId/runtime': typeof LayoutDockerRepoIdRuntimeRoute
  '/docker/$repoId/scans': typeof LayoutDockerRepoIdScansRoute
  '/infrastructure/$repoId/ansible': typeof LayoutInfrastructureRepoIdAnsibleRoute
  '/infrastructure/$repoId/cloud': typeof LayoutInfrastructureRepoIdCloudRoute
  '/infrastructure/$repoId/docker': typeof LayoutInfrastructureRepoIdDockerRoute
  '/infrastructure/$repoId/pull-requests': typeof LayoutInfrastructureRepoIdPullRequestsRoute
  '/infrastructure/$repoId/terraform': typeof LayoutInfrastructureRepoIdTerraformRoute
  '/repositories/$repoId/pull-requests': typeof LayoutRepositoriesRepoIdPullRequestsRoute
  '/repositories/$repoId/static-analysis': typeof LayoutRepositoriesRepoIdStaticAnalysisRoute
  '/repositories/$repoId/telemetry': typeof LayoutRepositoriesRepoIdTelemetryRoute
  '/docker/$repoId/': typeof LayoutDockerRepoIdIndexRoute
  '/infrastructure/$repoId/': typeof LayoutInfrastructureRepoIdIndexRoute
  '/repositories/$repoId/': typeof LayoutRepositoriesRepoIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/billing': typeof LayoutBillingRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/rules': typeof LayoutRulesRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/analyses/$analysisId': typeof LayoutAnalysesAnalysisIdRoute
  '/badges/ansible': typeof LayoutBadgesAnsibleRoute
  '/badges/docker': typeof LayoutBadgesDockerRoute
  '/badges/repositories': typeof LayoutBadgesRepositoriesRoute
  '/badges/terraform': typeof LayoutBadgesTerraformRoute
  '/docker/badges': typeof LayoutDockerBadgesRoute
  '/fixes/$fixId': typeof LayoutFixesFixIdRoute
  '/infrastructure/ansible': typeof LayoutInfrastructureAnsibleRoute
  '/infrastructure/badges': typeof LayoutInfrastructureBadgesRoute
  '/auth/github/app-callback': typeof AuthGithubAppCallbackRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/badges': typeof LayoutBadgesIndexRoute
  '/docker': typeof LayoutDockerIndexRoute
  '/infrastructure': typeof LayoutInfrastructureIndexRoute
  '/repositories': typeof LayoutRepositoriesIndexRoute
  '/docker/$repoId/analysis': typeof LayoutDockerRepoIdAnalysisRoute
  '/docker/$repoId/pull-requests': typeof LayoutDockerRepoIdPullRequestsRoute
  '/docker/$repoId/runtime': typeof LayoutDockerRepoIdRuntimeRoute
  '/docker/$repoId/scans': typeof LayoutDockerRepoIdScansRoute
  '/infrastructure/$repoId/ansible': typeof LayoutInfrastructureRepoIdAnsibleRoute
  '/infrastructure/$repoId/cloud': typeof LayoutInfrastructureRepoIdCloudRoute
  '/infrastructure/$repoId/docker': typeof LayoutInfrastructureRepoIdDockerRoute
  '/infrastructure/$repoId/pull-requests': typeof LayoutInfrastructureRepoIdPullRequestsRoute
  '/infrastructure/$repoId/terraform': typeof LayoutInfrastructureRepoIdTerraformRoute
  '/repositories/$repoId/pull-requests': typeof LayoutRepositoriesRepoIdPullRequestsRoute
  '/repositories/$repoId/static-analysis': typeof LayoutRepositoriesRepoIdStaticAnalysisRoute
  '/repositories/$repoId/telemetry': typeof LayoutRepositoriesRepoIdTelemetryRoute
  '/docker/$repoId': typeof LayoutDockerRepoIdIndexRoute
  '/infrastructure/$repoId': typeof LayoutInfrastructureRepoIdIndexRoute
  '/repositories/$repoId': typeof LayoutRepositoriesRepoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/badges': typeof LayoutBadgesRouteWithChildren
  '/_layout/billing': typeof LayoutBillingRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/docker': typeof LayoutDockerRouteWithChildren
  '/_layout/infrastructure': typeof LayoutInfrastructureRouteWithChildren
  '/_layout/repositories': typeof LayoutRepositoriesRouteWithChildren
  '/_layout/rules': typeof LayoutRulesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/analyses/$analysisId': typeof LayoutAnalysesAnalysisIdRoute
  '/_layout/badges/ansible': typeof LayoutBadgesAnsibleRoute
  '/_layout/badges/docker': typeof LayoutBadgesDockerRoute
  '/_layout/badges/repositories': typeof LayoutBadgesRepositoriesRoute
  '/_layout/badges/terraform': typeof LayoutBadgesTerraformRoute
  '/_layout/docker/$repoId': typeof LayoutDockerRepoIdRouteWithChildren
  '/_layout/docker/badges': typeof LayoutDockerBadgesRoute
  '/_layout/fixes/$fixId': typeof LayoutFixesFixIdRoute
  '/_layout/infrastructure/$repoId': typeof LayoutInfrastructureRepoIdRouteWithChildren
  '/_layout/infrastructure/ansible': typeof LayoutInfrastructureAnsibleRoute
  '/_layout/infrastructure/badges': typeof LayoutInfrastructureBadgesRoute
  '/_layout/repositories/$repoId': typeof LayoutRepositoriesRepoIdRouteWithChildren
  '/auth/github/app-callback': typeof AuthGithubAppCallbackRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/_layout/badges/': typeof LayoutBadgesIndexRoute
  '/_layout/docker/': typeof LayoutDockerIndexRoute
  '/_layout/infrastructure/': typeof LayoutInfrastructureIndexRoute
  '/_layout/repositories/': typeof LayoutRepositoriesIndexRoute
  '/_layout/docker/$repoId/analysis': typeof LayoutDockerRepoIdAnalysisRoute
  '/_layout/docker/$repoId/pull-requests': typeof LayoutDockerRepoIdPullRequestsRoute
  '/_layout/docker/$repoId/runtime': typeof LayoutDockerRepoIdRuntimeRoute
  '/_layout/docker/$repoId/scans': typeof LayoutDockerRepoIdScansRoute
  '/_layout/infrastructure/$repoId/ansible': typeof LayoutInfrastructureRepoIdAnsibleRoute
  '/_layout/infrastructure/$repoId/cloud': typeof LayoutInfrastructureRepoIdCloudRoute
  '/_layout/infrastructure/$repoId/docker': typeof LayoutInfrastructureRepoIdDockerRoute
  '/_layout/infrastructure/$repoId/pull-requests': typeof LayoutInfrastructureRepoIdPullRequestsRoute
  '/_layout/infrastructure/$repoId/terraform': typeof LayoutInfrastructureRepoIdTerraformRoute
  '/_layout/repositories/$repoId/pull-requests': typeof LayoutRepositoriesRepoIdPullRequestsRoute
  '/_layout/repositories/$repoId/static-analysis': typeof LayoutRepositoriesRepoIdStaticAnalysisRoute
  '/_layout/repositories/$repoId/telemetry': typeof LayoutRepositoriesRepoIdTelemetryRoute
  '/_layout/docker/$repoId/': typeof LayoutDockerRepoIdIndexRoute
  '/_layout/infrastructure/$repoId/': typeof LayoutInfrastructureRepoIdIndexRoute
  '/_layout/repositories/$repoId/': typeof LayoutRepositoriesRepoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/badges'
    | '/billing'
    | '/dashboard'
    | '/docker'
    | '/infrastructure'
    | '/repositories'
    | '/rules'
    | '/settings'
    | '/analyses/$analysisId'
    | '/badges/ansible'
    | '/badges/docker'
    | '/badges/repositories'
    | '/badges/terraform'
    | '/docker/$repoId'
    | '/docker/badges'
    | '/fixes/$fixId'
    | '/infrastructure/$repoId'
    | '/infrastructure/ansible'
    | '/infrastructure/badges'
    | '/repositories/$repoId'
    | '/auth/github/app-callback'
    | '/auth/github/callback'
    | '/badges/'
    | '/docker/'
    | '/infrastructure/'
    | '/repositories/'
    | '/docker/$repoId/analysis'
    | '/docker/$repoId/pull-requests'
    | '/docker/$repoId/runtime'
    | '/docker/$repoId/scans'
    | '/infrastructure/$repoId/ansible'
    | '/infrastructure/$repoId/cloud'
    | '/infrastructure/$repoId/docker'
    | '/infrastructure/$repoId/pull-requests'
    | '/infrastructure/$repoId/terraform'
    | '/repositories/$repoId/pull-requests'
    | '/repositories/$repoId/static-analysis'
    | '/repositories/$repoId/telemetry'
    | '/docker/$repoId/'
    | '/infrastructure/$repoId/'
    | '/repositories/$repoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/rules'
    | '/settings'
    | '/'
    | '/analyses/$analysisId'
    | '/badges/ansible'
    | '/badges/docker'
    | '/badges/repositories'
    | '/badges/terraform'
    | '/docker/badges'
    | '/fixes/$fixId'
    | '/infrastructure/ansible'
    | '/infrastructure/badges'
    | '/auth/github/app-callback'
    | '/auth/github/callback'
    | '/badges'
    | '/docker'
    | '/infrastructure'
    | '/repositories'
    | '/docker/$repoId/analysis'
    | '/docker/$repoId/pull-requests'
    | '/docker/$repoId/runtime'
    | '/docker/$repoId/scans'
    | '/infrastructure/$repoId/ansible'
    | '/infrastructure/$repoId/cloud'
    | '/infrastructure/$repoId/docker'
    | '/infrastructure/$repoId/pull-requests'
    | '/infrastructure/$repoId/terraform'
    | '/repositories/$repoId/pull-requests'
    | '/repositories/$repoId/static-analysis'
    | '/repositories/$repoId/telemetry'
    | '/docker/$repoId'
    | '/infrastructure/$repoId'
    | '/repositories/$repoId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/badges'
    | '/_layout/billing'
    | '/_layout/dashboard'
    | '/_layout/docker'
    | '/_layout/infrastructure'
    | '/_layout/repositories'
    | '/_layout/rules'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/analyses/$analysisId'
    | '/_layout/badges/ansible'
    | '/_layout/badges/docker'
    | '/_layout/badges/repositories'
    | '/_layout/badges/terraform'
    | '/_layout/docker/$repoId'
    | '/_layout/docker/badges'
    | '/_layout/fixes/$fixId'
    | '/_layout/infrastructure/$repoId'
    | '/_layout/infrastructure/ansible'
    | '/_layout/infrastructure/badges'
    | '/_layout/repositories/$repoId'
    | '/auth/github/app-callback'
    | '/auth/github/callback'
    | '/_layout/badges/'
    | '/_layout/docker/'
    | '/_layout/infrastructure/'
    | '/_layout/repositories/'
    | '/_layout/docker/$repoId/analysis'
    | '/_layout/docker/$repoId/pull-requests'
    | '/_layout/docker/$repoId/runtime'
    | '/_layout/docker/$repoId/scans'
    | '/_layout/infrastructure/$repoId/ansible'
    | '/_layout/infrastructure/$repoId/cloud'
    | '/_layout/infrastructure/$repoId/docker'
    | '/_layout/infrastructure/$repoId/pull-requests'
    | '/_layout/infrastructure/$repoId/terraform'
    | '/_layout/repositories/$repoId/pull-requests'
    | '/_layout/repositories/$repoId/static-analysis'
    | '/_layout/repositories/$repoId/telemetry'
    | '/_layout/docker/$repoId/'
    | '/_layout/infrastructure/$repoId/'
    | '/_layout/repositories/$repoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthGithubAppCallbackRoute: typeof AuthGithubAppCallbackRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/badges': {
      id: '/_layout/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof LayoutBadgesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/billing': {
      id: '/_layout/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof LayoutBillingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/docker': {
      id: '/_layout/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof LayoutDockerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/infrastructure': {
      id: '/_layout/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof LayoutInfrastructureRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/repositories': {
      id: '/_layout/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof LayoutRepositoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rules': {
      id: '/_layout/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof LayoutRulesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analyses/$analysisId': {
      id: '/_layout/analyses/$analysisId'
      path: '/analyses/$analysisId'
      fullPath: '/analyses/$analysisId'
      preLoaderRoute: typeof LayoutAnalysesAnalysisIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/badges/': {
      id: '/_layout/badges/'
      path: '/'
      fullPath: '/badges/'
      preLoaderRoute: typeof LayoutBadgesIndexRouteImport
      parentRoute: typeof LayoutBadgesRoute
    }
    '/_layout/badges/ansible': {
      id: '/_layout/badges/ansible'
      path: '/ansible'
      fullPath: '/badges/ansible'
      preLoaderRoute: typeof LayoutBadgesAnsibleRouteImport
      parentRoute: typeof LayoutBadgesRoute
    }
    '/_layout/badges/docker': {
      id: '/_layout/badges/docker'
      path: '/docker'
      fullPath: '/badges/docker'
      preLoaderRoute: typeof LayoutBadgesDockerRouteImport
      parentRoute: typeof LayoutBadgesRoute
    }
    '/_layout/badges/repositories': {
      id: '/_layout/badges/repositories'
      path: '/repositories'
      fullPath: '/badges/repositories'
      preLoaderRoute: typeof LayoutBadgesRepositoriesRouteImport
      parentRoute: typeof LayoutBadgesRoute
    }
    '/_layout/badges/terraform': {
      id: '/_layout/badges/terraform'
      path: '/terraform'
      fullPath: '/badges/terraform'
      preLoaderRoute: typeof LayoutBadgesTerraformRouteImport
      parentRoute: typeof LayoutBadgesRoute
    }
    '/_layout/docker/': {
      id: '/_layout/docker/'
      path: '/'
      fullPath: '/docker/'
      preLoaderRoute: typeof LayoutDockerIndexRouteImport
      parentRoute: typeof LayoutDockerRoute
    }
    '/_layout/docker/$repoId': {
      id: '/_layout/docker/$repoId'
      path: '/$repoId'
      fullPath: '/docker/$repoId'
      preLoaderRoute: typeof LayoutDockerRepoIdRouteImport
      parentRoute: typeof LayoutDockerRoute
    }
    '/_layout/docker/badges': {
      id: '/_layout/docker/badges'
      path: '/badges'
      fullPath: '/docker/badges'
      preLoaderRoute: typeof LayoutDockerBadgesRouteImport
      parentRoute: typeof LayoutDockerRoute
    }
    '/_layout/fixes/$fixId': {
      id: '/_layout/fixes/$fixId'
      path: '/fixes/$fixId'
      fullPath: '/fixes/$fixId'
      preLoaderRoute: typeof LayoutFixesFixIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/infrastructure/': {
      id: '/_layout/infrastructure/'
      path: '/'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof LayoutInfrastructureIndexRouteImport
      parentRoute: typeof LayoutInfrastructureRoute
    }
    '/_layout/infrastructure/$repoId': {
      id: '/_layout/infrastructure/$repoId'
      path: '/$repoId'
      fullPath: '/infrastructure/$repoId'
      preLoaderRoute: typeof LayoutInfrastructureRepoIdRouteImport
      parentRoute: typeof LayoutInfrastructureRoute
    }
    '/_layout/infrastructure/ansible': {
      id: '/_layout/infrastructure/ansible'
      path: '/ansible'
      fullPath: '/infrastructure/ansible'
      preLoaderRoute: typeof LayoutInfrastructureAnsibleRouteImport
      parentRoute: typeof LayoutInfrastructureRoute
    }
    '/_layout/infrastructure/badges': {
      id: '/_layout/infrastructure/badges'
      path: '/badges'
      fullPath: '/infrastructure/badges'
      preLoaderRoute: typeof LayoutInfrastructureBadgesRouteImport
      parentRoute: typeof LayoutInfrastructureRoute
    }
    '/_layout/repositories/': {
      id: '/_layout/repositories/'
      path: '/'
      fullPath: '/repositories/'
      preLoaderRoute: typeof LayoutRepositoriesIndexRouteImport
      parentRoute: typeof LayoutRepositoriesRoute
    }
    '/_layout/repositories/$repoId': {
      id: '/_layout/repositories/$repoId'
      path: '/$repoId'
      fullPath: '/repositories/$repoId'
      preLoaderRoute: typeof LayoutRepositoriesRepoIdRouteImport
      parentRoute: typeof LayoutRepositoriesRoute
    }
    '/auth/github/app-callback': {
      id: '/auth/github/app-callback'
      path: '/auth/github/app-callback'
      fullPath: '/auth/github/app-callback'
      preLoaderRoute: typeof AuthGithubAppCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/docker/$repoId/': {
      id: '/_layout/docker/$repoId/'
      path: '/'
      fullPath: '/docker/$repoId/'
      preLoaderRoute: typeof LayoutDockerRepoIdIndexRouteImport
      parentRoute: typeof LayoutDockerRepoIdRoute
    }
    '/_layout/docker/$repoId/analysis': {
      id: '/_layout/docker/$repoId/analysis'
      path: '/analysis'
      fullPath: '/docker/$repoId/analysis'
      preLoaderRoute: typeof LayoutDockerRepoIdAnalysisRouteImport
      parentRoute: typeof LayoutDockerRepoIdRoute
    }
    '/_layout/docker/$repoId/pull-requests': {
      id: '/_layout/docker/$repoId/pull-requests'
      path: '/pull-requests'
      fullPath: '/docker/$repoId/pull-requests'
      preLoaderRoute: typeof LayoutDockerRepoIdPullRequestsRouteImport
      parentRoute: typeof LayoutDockerRepoIdRoute
    }
    '/_layout/docker/$repoId/runtime': {
      id: '/_layout/docker/$repoId/runtime'
      path: '/runtime'
      fullPath: '/docker/$repoId/runtime'
      preLoaderRoute: typeof LayoutDockerRepoIdRuntimeRouteImport
      parentRoute: typeof LayoutDockerRepoIdRoute
    }
    '/_layout/docker/$repoId/scans': {
      id: '/_layout/docker/$repoId/scans'
      path: '/scans'
      fullPath: '/docker/$repoId/scans'
      preLoaderRoute: typeof LayoutDockerRepoIdScansRouteImport
      parentRoute: typeof LayoutDockerRepoIdRoute
    }
    '/_layout/infrastructure/$repoId/': {
      id: '/_layout/infrastructure/$repoId/'
      path: '/'
      fullPath: '/infrastructure/$repoId/'
      preLoaderRoute: typeof LayoutInfrastructureRepoIdIndexRouteImport
      parentRoute: typeof LayoutInfrastructureRepoIdRoute
    }
    '/_layout/infrastructure/$repoId/ansible': {
      id: '/_layout/infrastructure/$repoId/ansible'
      path: '/ansible'
      fullPath: '/infrastructure/$repoId/ansible'
      preLoaderRoute: typeof LayoutInfrastructureRepoIdAnsibleRouteImport
      parentRoute: typeof LayoutInfrastructureRepoIdRoute
    }
    '/_layout/infrastructure/$repoId/cloud': {
      id: '/_layout/infrastructure/$repoId/cloud'
      path: '/cloud'
      fullPath: '/infrastructure/$repoId/cloud'
      preLoaderRoute: typeof LayoutInfrastructureRepoIdCloudRouteImport
      parentRoute: typeof LayoutInfrastructureRepoIdRoute
    }
    '/_layout/infrastructure/$repoId/docker': {
      id: '/_layout/infrastructure/$repoId/docker'
      path: '/docker'
      fullPath: '/infrastructure/$repoId/docker'
      preLoaderRoute: typeof LayoutInfrastructureRepoIdDockerRouteImport
      parentRoute: typeof LayoutInfrastructureRepoIdRoute
    }
    '/_layout/infrastructure/$repoId/pull-requests': {
      id: '/_layout/infrastructure/$repoId/pull-requests'
      path: '/pull-requests'
      fullPath: '/infrastructure/$repoId/pull-requests'
      preLoaderRoute: typeof LayoutInfrastructureRepoIdPullRequestsRouteImport
      parentRoute: typeof LayoutInfrastructureRepoIdRoute
    }
    '/_layout/infrastructure/$repoId/terraform': {
      id: '/_layout/infrastructure/$repoId/terraform'
      path: '/terraform'
      fullPath: '/infrastructure/$repoId/terraform'
      preLoaderRoute: typeof LayoutInfrastructureRepoIdTerraformRouteImport
      parentRoute: typeof LayoutInfrastructureRepoIdRoute
    }
    '/_layout/repositories/$repoId/': {
      id: '/_layout/repositories/$repoId/'
      path: '/'
      fullPath: '/repositories/$repoId/'
      preLoaderRoute: typeof LayoutRepositoriesRepoIdIndexRouteImport
      parentRoute: typeof LayoutRepositoriesRepoIdRoute
    }
    '/_layout/repositories/$repoId/pull-requests': {
      id: '/_layout/repositories/$repoId/pull-requests'
      path: '/pull-requests'
      fullPath: '/repositories/$repoId/pull-requests'
      preLoaderRoute: typeof LayoutRepositoriesRepoIdPullRequestsRouteImport
      parentRoute: typeof LayoutRepositoriesRepoIdRoute
    }
    '/_layout/repositories/$repoId/static-analysis': {
      id: '/_layout/repositories/$repoId/static-analysis'
      path: '/static-analysis'
      fullPath: '/repositories/$repoId/static-analysis'
      preLoaderRoute: typeof LayoutRepositoriesRepoIdStaticAnalysisRouteImport
      parentRoute: typeof LayoutRepositoriesRepoIdRoute
    }
    '/_layout/repositories/$repoId/telemetry': {
      id: '/_layout/repositories/$repoId/telemetry'
      path: '/telemetry'
      fullPath: '/repositories/$repoId/telemetry'
      preLoaderRoute: typeof LayoutRepositoriesRepoIdTelemetryRouteImport
      parentRoute: typeof LayoutRepositoriesRepoIdRoute
    }
  }
}

interface LayoutBadgesRouteChildren {
  LayoutBadgesAnsibleRoute: typeof LayoutBadgesAnsibleRoute
  LayoutBadgesDockerRoute: typeof LayoutBadgesDockerRoute
  LayoutBadgesRepositoriesRoute: typeof LayoutBadgesRepositoriesRoute
  LayoutBadgesTerraformRoute: typeof LayoutBadgesTerraformRoute
  LayoutBadgesIndexRoute: typeof LayoutBadgesIndexRoute
}

const LayoutBadgesRouteChildren: LayoutBadgesRouteChildren = {
  LayoutBadgesAnsibleRoute: LayoutBadgesAnsibleRoute,
  LayoutBadgesDockerRoute: LayoutBadgesDockerRoute,
  LayoutBadgesRepositoriesRoute: LayoutBadgesRepositoriesRoute,
  LayoutBadgesTerraformRoute: LayoutBadgesTerraformRoute,
  LayoutBadgesIndexRoute: LayoutBadgesIndexRoute,
}

const LayoutBadgesRouteWithChildren = LayoutBadgesRoute._addFileChildren(
  LayoutBadgesRouteChildren,
)

interface LayoutDockerRepoIdRouteChildren {
  LayoutDockerRepoIdAnalysisRoute: typeof LayoutDockerRepoIdAnalysisRoute
  LayoutDockerRepoIdPullRequestsRoute: typeof LayoutDockerRepoIdPullRequestsRoute
  LayoutDockerRepoIdRuntimeRoute: typeof LayoutDockerRepoIdRuntimeRoute
  LayoutDockerRepoIdScansRoute: typeof LayoutDockerRepoIdScansRoute
  LayoutDockerRepoIdIndexRoute: typeof LayoutDockerRepoIdIndexRoute
}

const LayoutDockerRepoIdRouteChildren: LayoutDockerRepoIdRouteChildren = {
  LayoutDockerRepoIdAnalysisRoute: LayoutDockerRepoIdAnalysisRoute,
  LayoutDockerRepoIdPullRequestsRoute: LayoutDockerRepoIdPullRequestsRoute,
  LayoutDockerRepoIdRuntimeRoute: LayoutDockerRepoIdRuntimeRoute,
  LayoutDockerRepoIdScansRoute: LayoutDockerRepoIdScansRoute,
  LayoutDockerRepoIdIndexRoute: LayoutDockerRepoIdIndexRoute,
}

const LayoutDockerRepoIdRouteWithChildren =
  LayoutDockerRepoIdRoute._addFileChildren(LayoutDockerRepoIdRouteChildren)

interface LayoutDockerRouteChildren {
  LayoutDockerRepoIdRoute: typeof LayoutDockerRepoIdRouteWithChildren
  LayoutDockerBadgesRoute: typeof LayoutDockerBadgesRoute
  LayoutDockerIndexRoute: typeof LayoutDockerIndexRoute
}

const LayoutDockerRouteChildren: LayoutDockerRouteChildren = {
  LayoutDockerRepoIdRoute: LayoutDockerRepoIdRouteWithChildren,
  LayoutDockerBadgesRoute: LayoutDockerBadgesRoute,
  LayoutDockerIndexRoute: LayoutDockerIndexRoute,
}

const LayoutDockerRouteWithChildren = LayoutDockerRoute._addFileChildren(
  LayoutDockerRouteChildren,
)

interface LayoutInfrastructureRepoIdRouteChildren {
  LayoutInfrastructureRepoIdAnsibleRoute: typeof LayoutInfrastructureRepoIdAnsibleRoute
  LayoutInfrastructureRepoIdCloudRoute: typeof LayoutInfrastructureRepoIdCloudRoute
  LayoutInfrastructureRepoIdDockerRoute: typeof LayoutInfrastructureRepoIdDockerRoute
  LayoutInfrastructureRepoIdPullRequestsRoute: typeof LayoutInfrastructureRepoIdPullRequestsRoute
  LayoutInfrastructureRepoIdTerraformRoute: typeof LayoutInfrastructureRepoIdTerraformRoute
  LayoutInfrastructureRepoIdIndexRoute: typeof LayoutInfrastructureRepoIdIndexRoute
}

const LayoutInfrastructureRepoIdRouteChildren: LayoutInfrastructureRepoIdRouteChildren =
  {
    LayoutInfrastructureRepoIdAnsibleRoute:
      LayoutInfrastructureRepoIdAnsibleRoute,
    LayoutInfrastructureRepoIdCloudRoute: LayoutInfrastructureRepoIdCloudRoute,
    LayoutInfrastructureRepoIdDockerRoute:
      LayoutInfrastructureRepoIdDockerRoute,
    LayoutInfrastructureRepoIdPullRequestsRoute:
      LayoutInfrastructureRepoIdPullRequestsRoute,
    LayoutInfrastructureRepoIdTerraformRoute:
      LayoutInfrastructureRepoIdTerraformRoute,
    LayoutInfrastructureRepoIdIndexRoute: LayoutInfrastructureRepoIdIndexRoute,
  }

const LayoutInfrastructureRepoIdRouteWithChildren =
  LayoutInfrastructureRepoIdRoute._addFileChildren(
    LayoutInfrastructureRepoIdRouteChildren,
  )

interface LayoutInfrastructureRouteChildren {
  LayoutInfrastructureRepoIdRoute: typeof LayoutInfrastructureRepoIdRouteWithChildren
  LayoutInfrastructureAnsibleRoute: typeof LayoutInfrastructureAnsibleRoute
  LayoutInfrastructureBadgesRoute: typeof LayoutInfrastructureBadgesRoute
  LayoutInfrastructureIndexRoute: typeof LayoutInfrastructureIndexRoute
}

const LayoutInfrastructureRouteChildren: LayoutInfrastructureRouteChildren = {
  LayoutInfrastructureRepoIdRoute: LayoutInfrastructureRepoIdRouteWithChildren,
  LayoutInfrastructureAnsibleRoute: LayoutInfrastructureAnsibleRoute,
  LayoutInfrastructureBadgesRoute: LayoutInfrastructureBadgesRoute,
  LayoutInfrastructureIndexRoute: LayoutInfrastructureIndexRoute,
}

const LayoutInfrastructureRouteWithChildren =
  LayoutInfrastructureRoute._addFileChildren(LayoutInfrastructureRouteChildren)

interface LayoutRepositoriesRepoIdRouteChildren {
  LayoutRepositoriesRepoIdPullRequestsRoute: typeof LayoutRepositoriesRepoIdPullRequestsRoute
  LayoutRepositoriesRepoIdStaticAnalysisRoute: typeof LayoutRepositoriesRepoIdStaticAnalysisRoute
  LayoutRepositoriesRepoIdTelemetryRoute: typeof LayoutRepositoriesRepoIdTelemetryRoute
  LayoutRepositoriesRepoIdIndexRoute: typeof LayoutRepositoriesRepoIdIndexRoute
}

const LayoutRepositoriesRepoIdRouteChildren: LayoutRepositoriesRepoIdRouteChildren =
  {
    LayoutRepositoriesRepoIdPullRequestsRoute:
      LayoutRepositoriesRepoIdPullRequestsRoute,
    LayoutRepositoriesRepoIdStaticAnalysisRoute:
      LayoutRepositoriesRepoIdStaticAnalysisRoute,
    LayoutRepositoriesRepoIdTelemetryRoute:
      LayoutRepositoriesRepoIdTelemetryRoute,
    LayoutRepositoriesRepoIdIndexRoute: LayoutRepositoriesRepoIdIndexRoute,
  }

const LayoutRepositoriesRepoIdRouteWithChildren =
  LayoutRepositoriesRepoIdRoute._addFileChildren(
    LayoutRepositoriesRepoIdRouteChildren,
  )

interface LayoutRepositoriesRouteChildren {
  LayoutRepositoriesRepoIdRoute: typeof LayoutRepositoriesRepoIdRouteWithChildren
  LayoutRepositoriesIndexRoute: typeof LayoutRepositoriesIndexRoute
}

const LayoutRepositoriesRouteChildren: LayoutRepositoriesRouteChildren = {
  LayoutRepositoriesRepoIdRoute: LayoutRepositoriesRepoIdRouteWithChildren,
  LayoutRepositoriesIndexRoute: LayoutRepositoriesIndexRoute,
}

const LayoutRepositoriesRouteWithChildren =
  LayoutRepositoriesRoute._addFileChildren(LayoutRepositoriesRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBadgesRoute: typeof LayoutBadgesRouteWithChildren
  LayoutBillingRoute: typeof LayoutBillingRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutDockerRoute: typeof LayoutDockerRouteWithChildren
  LayoutInfrastructureRoute: typeof LayoutInfrastructureRouteWithChildren
  LayoutRepositoriesRoute: typeof LayoutRepositoriesRouteWithChildren
  LayoutRulesRoute: typeof LayoutRulesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAnalysesAnalysisIdRoute: typeof LayoutAnalysesAnalysisIdRoute
  LayoutFixesFixIdRoute: typeof LayoutFixesFixIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBadgesRoute: LayoutBadgesRouteWithChildren,
  LayoutBillingRoute: LayoutBillingRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutDockerRoute: LayoutDockerRouteWithChildren,
  LayoutInfrastructureRoute: LayoutInfrastructureRouteWithChildren,
  LayoutRepositoriesRoute: LayoutRepositoriesRouteWithChildren,
  LayoutRulesRoute: LayoutRulesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAnalysesAnalysisIdRoute: LayoutAnalysesAnalysisIdRoute,
  LayoutFixesFixIdRoute: LayoutFixesFixIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthGithubAppCallbackRoute: AuthGithubAppCallbackRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
