#!/usr/bin/env python3
"""Write deploy/coolify/compose.dev.yml: the Coolify stack, built from source.

The dev environment is the one Coolify deploys by itself: its resource tracks
``main`` with auto-deploy on, so it has to build what it runs. Staging and
production never build — they pull the images ``images.yml`` publishes for a
release — so ``deploy/coolify/compose.yml`` stays pull-only and the build lives
in this generated copy. Generating it, rather than keeping a second
hand-written stack, is what keeps dev running the same services, limits and
Coolify magic variables as the environments it previews.

Every service that runs one of the two GHCR images gets a local tag, a
``build:`` section and ``pull_policy: build``, and ``ENVIRONMENT`` defaults to
``dev`` rather than ``production``. Build contexts are relative to
the compose file's own directory, ``deploy/coolify/``, hence ``../..``.

This is plain YAML rather than ``docker compose config``: the stack uses
Coolify-only keys (a volume's ``content``) that Compose itself rejects.
Comments and anchors do not survive the round trip, which is why the file says
it is generated.

Usage:

    scripts/generate_compose_dev.py          # rewrite compose.dev.yml
    scripts/generate_compose_dev.py --check  # fail if it is out of date
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "deploy" / "coolify" / "compose.yml"
TARGET = ROOT / "deploy" / "coolify" / "compose.dev.yml"

# GHCR image name (without registry or tag) -> how dev builds it instead.
BUILDS: dict[str, dict[str, str]] = {
    "greensecops-backend": {"context": "../..", "dockerfile": "backend/Dockerfile"},
    "greensecops-opa": {"context": "../..", "dockerfile": "opa/Dockerfile"},
}

HEADER = (
    "# GENERATED by scripts/generate_compose_dev.py from deploy/coolify/compose.yml"
    " — do not edit.\n"
    "# The dev environment's Coolify stack: compose.yml, with its images built"
    " from source.\n"
)


class _NoAliasDumper(yaml.SafeDumper):
    """Write shared mappings out in full: anchors would only make it harder to read."""

    def ignore_aliases(self, data: Any) -> bool:
        return True


def _default_environment_to_dev(service: dict[str, Any]) -> None:
    """Default ENVIRONMENT to dev, where compose.yml defaults it to production."""
    environment = service.get("environment")
    if isinstance(environment, list):
        for i, entry in enumerate(environment):
            if str(entry).startswith("ENVIRONMENT="):
                environment[i] = "ENVIRONMENT=${ENVIRONMENT:-dev}"
    elif isinstance(environment, dict) and "ENVIRONMENT" in environment:
        environment["ENVIRONMENT"] = "${ENVIRONMENT:-dev}"


def render() -> str:
    stack = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    found: set[str] = set()
    for service in stack["services"].values():
        image = str(service.get("image", ""))
        # ${IMAGE_REGISTRY:-ghcr.io/owner}/greensecops-backend:${TAG:-latest}
        repository = image.rsplit("/", 1)[-1].split(":", 1)[0]
        build = BUILDS.get(repository)
        if build is None:
            continue
        service["image"] = f"{repository}:dev"
        service["pull_policy"] = "build"
        service["build"] = dict(build)
        _default_environment_to_dev(service)
        found.add(repository)
    missing = set(BUILDS) - found
    if missing:
        sys.exit(f"compose.yml no longer runs {sorted(missing)}; update BUILDS here.")
    body = yaml.dump(
        stack,
        Dumper=_NoAliasDumper,
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )
    return HEADER + body


def main() -> int:
    rendered = render()
    if sys.argv[1:] == ["--check"]:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(
                f"::error file={TARGET.relative_to(ROOT)}::{TARGET.relative_to(ROOT)} is "
                "out of date with compose.yml beside it. Run "
                "scripts/generate_compose_dev.py and commit the result."
            )
            return 1
        print(f"{TARGET.relative_to(ROOT)} is up to date.")
        return 0
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
