name: Labels
true:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - labeled
    - unlabeled
permissions: {}
jobs:
  labeler:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - &id001
      name: GreenSecOps Telemetry
      uses: greensecops/greensecops-action@v1
      with:
        greensecops_url: ${{ vars.GREENSECOPS_URL }}
    - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213
      if: ${{ github.event.action != 'labeled' && github.event.action != 'unlabeled'
        }}
    - run: echo "Done adding labels"
  check-labels:
    needs:
    - labeler
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - *id001
    - uses: agilepathway/label-checker@c3d16ad512e7cea5961df85ff2486bb774caf3c5
      with:
        one_of: breaking,security,feature,bug,refactor,upgrade,docs,lang-all,internal
        repo_token: ${{ secrets.GITHUB_TOKEN }}
