name: Zizmor
true:
  push:
    branches:
    - master
  workflow_dispatch: null
permissions: {}
jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      security-events: write
    steps:
    - name: GreenSecOps Telemetry
      uses: greensecops/greensecops-action@v1
      with:
        greensecops_url: ${{ vars.GREENSECOPS_URL }}
    - name: Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      with:
        persist-credentials: false
    - name: Run zizmor
      uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d
